### ISSUE TITLE
Respect CC

### ISSUE THREAD

**Issue by kirbyfan64** [objeck/objeck-lang#1]
Right now, I can't try to build Objeck with Clang because the deploy script ignores any options passed to it. Could some of the lines be changed to something like this:

```bash
...
make clean; make -j3 "$@"
```

This would allow setting the CC variable.

**Comment by objeck** [comment]
Hi, the distro does build with Clang under OS X. What binary are you trying to build? What does the makefile look like?

Thanks,
Randy

**Comment by kirbyfan64** [comment]
I'm just trying to build the latest Objeck from Git using `deploy.sh`. The makefiles manually set CC (to a C++ compiler, which is actually supposed to be set in the CXX variable), so a normal:

```
$ CXX=clang++ ./deploy.sh
```

doesn't use Clang.

**Comment by kirbyfan64** [comment]
@objeck Nevermind. After trying to fix it myself, I opened a giant can of worms and messed up several makefiles.
