### ISSUE TITLE
Objeck syntax highlighting for BowPad

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [objeck/objeck-lang#108]
Another Scintilla based editor @objeck, but with a ribbon based UI.

https://github.com/stefankueng/BowPad

https://github.com/stefankueng/BowPad/issues/302

**Comment by objeck** [comment]
I like the editor

**Comment by 1997tn** [comment]
> I like the editor

BowPad uses Lexilla, user defined lexer is not powerful enough to correctly highlight Objeck code. You should better close this issue and OP should better wait for https://github.com/ScintillaOrg/lexilla/issues/121. You could do nothing to help, it's not your problem @objeck

**Comment by objeck** [comment]
Thank you
