### ISSUE TITLE
Cygwin?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#138]
Cygwin is a weird platform. I could build the POSIX version of Objeck (Makefile.amd64) on Cygwin without any major changes, only has to add `-D_GNU_SOURCE` to ARGS. This is weird because `-D_GNU_SOURCE` seems to defined by default on Linux. I have no idea why Cygwin doesn't define it by default. It aimed to provide a POSIX like environment on Windows anyway. Another thing even more weird, wchar_t on POSIX is 4 bytes isn't it? On Cygwin it's 2 bytes like Windows. This is the reason why I have the POSIX version of Objeck compiled on Cygwin but can't run it as it always throws an exception when running obr (obc worked fine though, it's weird).

Cygwin also doesn't have unixodbc. It's weird. It aimed to be POSIX like, but doesn't have any packages for unixodbc. There are various odbc packages but all are marked as unmaintained, I don't know if these packages provide the same feature as unixodbc on MSYS2. The SDL2 packages on Cygwin are also marked as unmaintained. This is the reason why I have to edit deploy_posix.sh to comment out odbc and SDL from building. If you ever want to support Cygwin, I think we need separate makefiles and build script for it (Makefile.cygwin.amd64 and deploy_cygwin.sh).

p/s: End of my small adventure with Cygwin. Almost forgot, Cygwin is defined as `__CYGWIN__`

**Comment by iahung** [comment]
@objeck @rhollines

**Comment by objeck** [comment]
Thanks for your efforts! Right now, I do not plan to add another Windows target.

**Comment by iahung** [comment]
> Thanks for your efforts! Right now, I do not plan to add another Windows target.

On Cygwin, `_WIN32` is not defined. Cygwin is a POSIX target, the only different is on Cygwin wchar_t is 2 bytes like Windows, not 4 bytes like POSIX.

**Comment by iahung** [comment]
Cygwin's mbstowcs is broken, we need to use Windows API's MultiByteToWideChar. Since everything is already there, I tried a bit of macro hacks. It's not simple as it seems. OpenSSL conflicts with windows.h on Cygwin. I can't include windows.h but luckily stringapiset.h silented the OpenSSL errors. Another problem arises, stringapiset.h pulls in minwindef.h that defined `_WIN64`, this messed everything up. To support Cygwin is very simple, we have to had our own implementation of mbstowcs/MultiByteToWideChar that is independent to both POSIX's mbstowcs and Windows' MultiByteToWideChar for target `__CYGWIN__`. I'm not a programmer so I can't do this. But you can do this @objeck @rhollines 

https://github.com/wxWidgets/wxWidgets/issues/10526

**Comment by iahung** [comment]
No need Cygwin. I got MSYS2 working now.
