### ISSUE TITLE
native broken on Cygwin

### ISSUE THREAD

**Issue by tn1997tn** [objeck/objeck-lang#145]
This code will failed to run, obr will silently exit without any output:

```
class Foo {
	function : Main(args : String[]) ~ Nil {
		Brun();
	}

	function : native : Brun() ~ Nil {
		N := 100000;

		box := Int->New[N];
		#box->Size()->PrintLine();
		for(i := 0; i < N; i += 1;) {
			box[i] := N - i;
			box[i]->Print();
		};
		""->PrintLine();

		"--------------------"->PrintLine();
		for(i := 0; i < N - 1; i += 1;) {
			for(j := 0; j < N - 1; j += 1;) {
				if(box[j] > box[j+1]) {
					x := box[j];
					box[j] := box[j+1];
					box[j+1] := x;
				};
			};
		};
		for(i := 0; i < N; i += 1;) {
			box[i]->Print();
		};
		""->PrintLine();
	}
}

```

Remove `native` and it will work (albeit very slow):

```
class Foo {
	function : Main(args : String[]) ~ Nil {
		Brun();
	}

	function : Brun() ~ Nil {
		N := 100000;

		box := Int->New[N];
		#box->Size()->PrintLine();
		for(i := 0; i < N; i += 1;) {
			box[i] := N - i;
			box[i]->Print();
		};
		""->PrintLine();

		"--------------------"->PrintLine();
		for(i := 0; i < N - 1; i += 1;) {
			for(j := 0; j < N - 1; j += 1;) {
				if(box[j] > box[j+1]) {
					x := box[j];
					box[j] := box[j+1];
					box[j+1] := x;
				};
			};
		};
		for(i := 0; i < N; i += 1;) {
			box[i]->Print();
		};
		""->PrintLine();
	}
}

```

**Comment by iahung** [comment]
Maybe this commit: https://github.com/objeck/objeck-lang/commit/7281e854d53f41323c09b051f2b2610c080a4777

But without it, obr will simply exit with `Unable to mprotect`. On Cygwin, `PAGE_SIZE` is defined as:

```
#define __PAGESIZE 65536
#define PAGESIZE __PAGESIZE
#define PAGE_SIZE PAGESIZE
```

I guess `PAGE_SIZE` as 4096 like defined by Objeck is too low so I added the macro to use the `PAGE_SIZE` defined by Cygwin. This is indeed solved `Unable to mprotect`.

**Comment by objeck** [comment]
The page size is platform-dependent, normally processor-dependent, and Cygwin is a hybrid system. Does the system now run on Cygwin with JIT compiler support?

**Comment by iahung** [comment]
> The page size is platform-dependent, normally processor-dependent, and Cygwin is a hybrid system.

You hardcoded it to 4096 in `jit_amd_lp64.h`:

```
#ifndef I386_PGBYTES
#define PAGE_SIZE 4096
#endif
```

**Comment by objeck** [comment]
Yes, as #defined, i.e. can be redefined as needed. The page size for ARM64 and AMD64 is 4k.

**Comment by iahung** [comment]
> Yes, as a #define, i.e. can be redefined as needed. The page size for ARM64 and AMD64 is 4k.

So it's a naming conflict? Objeck uses `PAGE_SIZE` internally but unfortunately `PAGE_SIZE` already used by Cygwin's limits.h. Or Objeck redefines limits.h's `PAGE_SIZE`?

**Comment by iahung** [comment]
If I revert https://github.com/objeck/objeck-lang/commit/7281e854d53f41323c09b051f2b2610c080a4777, it will be stuck with `Unable to mprotect`. If I applied https://github.com/objeck/objeck-lang/commit/7281e854d53f41323c09b051f2b2610c080a4777 then it will failed to run code that uses `native`.

About the error `Unable to mprotect`. I have added code to check for errno. It's errno 22. I'm lost. I have no idea why it's that way. This is the first time I tried to be programmer. But it turned out too badly. Please revert all of my PRs. Thank you @objeck @rhollines

**Comment by objeck** [comment]
Maybe change ``PAGE_SIZE`` to ``JIT_PAGE_SIZE``. There are no naming conflicts on other platforms. Frankly, Cygwin seems messy.

**Comment by tn1997tn** [comment]
> Maybe change `PAGE_SIZE` to `JIT_PAGE_SIZE`. There are no naming conflicts on other platforms.

Changing name doesn't work. Still `Unable to mprotect`. Cygwin doesn't like the value 4096.

> Frankly, Cygwin seems messy with limited benefits.

Agreed. He was right to ask reverting his PRs (also means remove Cygwin support).

**Comment by iahung** [comment]
After many days, I find out why it failed on Cygwin:

https://cygwin.com/pipermail/cygwin-developers/2020-July/011913.html

https://cygwin.com/pipermail/cygwin/2002-January/068158.html

Maybe it's better to just remove Cygwin support than dealing with all of this mess @objeck @rhollines 

If you are OK with this, I will make a PR to remove Cygwin support.
