### ISSUE TITLE
Mysterious error with makefile

### ISSUE THREAD

**Issue by iahunq** [objeck/objeck-lang#153]
Have a look at this makefile:

https://github.com/objeck/objeck-lang/blob/master/core/shared/make/Makefile.msys2-ucrt.amd64

Something really strange happened. The first time you run `./deploy_msys2-ucrt.sh` it will present you this error and it will fail to build `obc.exe`:

```
cp logger.a ../compiler; cp logger.a ../vm; cp logger.a ../release/WindowsLauncher/AppLauncher
cp: cannot create regular file '../release/WindowsLauncher/AppLauncher': No such file or directory
```

Seems as simple as you are copying file into an nonexistent directory, isn't it?

But if you run `./deploy_msys2-ucrt.sh` the second time, the error will mysteriously disappeared and you have `obc.exe` build as expected!

**Comment by objeck** [comment]
Should be fixed
