### ISSUE TITLE
语法设计不友好

### ISSUE THREAD

**Issue by zoujiaqing** [objeck/objeck-lang#161]
你这样的写法也太 php 了：
```
a->b;
```
简洁一点：
```
a.b;
```

**Comment by objeck** [comment]
``3.1415.ToString();`` vs. ``3.1415->ToString();``

**Comment by tn1997tn** [comment]
https://github.com/objeck/objeck-lang/discussions/134

**Comment by objeck** [comment]
It is the language syntax
