### ISSUE TITLE
Int->Clamp

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#168]
`Int->Clamp(num, min, max);`

`num->Clamp(min, max);`

Clamp this integer between the min and max. If its less than min then return min, if its greater than max return max, otherwise return this integer itself.

Clamp should be added to other integer types too.

**Comment by objeck** [comment]
Mmm, k

**Comment by tn1997tn** [comment]
Did you get the idea from `std::clamp`?

https://en.cppreference.com/w/cpp/algorithm/clamp

p/s: a quick Google search tells me Java doesn't have this clamp function.

**Comment by objeck** [comment]
Documentation, yes; implementation, no.

**Comment by hgntn** [comment]
> Did you get the idea from `std::clamp`?
> 
> https://en.cppreference.com/w/cpp/algorithm/clamp
> 
> p/s: a quick Google search tells me Java doesn't have this clamp function.

C# has Clamp function: https://learn.microsoft.com/en-us/dotnet/api/system.math.clamp?view=net-7.0

**Comment by objeck** [comment]
Released in 9fc3c7e
