### ISSUE TITLE
Rename SquareRoot to Sqrt

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#170]
All languages I know use `Sqrt`. Everyone know what `Sqrt` means. Using `SquareRoot` is pointless. There are many abbreviations used through out the API like `IsNeg` and `NotNeg`. Given the `SquareRoot` convention, shouldn't them be `IsNegative` and `NotNegative`? The API is so arbitrary and inconsistent.

**Comment by objeck** [comment]
Ok, no strong opinion on the matter

**Comment by objeck** [comment]
Released in 9fc3c7e
