### ISSUE TITLE
Objeck for 32 bit environment

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#173]
README.md said JIT is only available for arm64 and x86_64. So from what I understand I could build and use Objeck on 32 bit environment normally without JIT? Please correct me if I was wrong.

**Comment by objeck** [comment]
The current VM only supports arm64 and x86_64 targets. If the VM is compiled with for a 32-bit target the VM will crash. The VM expects doubles and integers to be a fixed 64 bits. 

32-bit support for IA-32 and ARMv7 was removed after v6.4.3 88382163d0ffe4600506d0af3e870e1a555f127f.
