### ISSUE TITLE
Integer power

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#177]
Please add a `Pow` method to integer types. This `Pow` method takes an integer typed value and returns an Int value, unlike the `Pow` method of Float that always takes a Float value and return a Float value.

https://github.com/objeck/objeck-lang/issues/176

**Comment by objeck** [comment]
Added

**Comment by hgntn** [comment]
> Added

The output should be an Int. You called `Float->Pow(b, r)` so the output is still a Float.
