### ISSUE TITLE
Add Exp to Float

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#180]
I don't understand why such a commonly used function like Exp is not included. Objeck doesn't have exponential function but has useless stuffs like `Factorial` and `DoubleFactorial` as part of the standard math library! https://github.com/objeck/objeck-lang/issues/171

**Comment by hgntn** [comment]
> What is the need for all of the math functions? Not "hard" to add; just time required.

C/C++/Java have these functions. Almost all of the programming languages out there have these functions. Any scientific calculators like CASIO have these functions.

**Comment by objeck** [comment]
In [b182421](https://github.com/objeck/objeck-lang/commit/b1824214e797d3ecaaa07c69f9bb45cf66e2bbf5)
