### ISSUE TITLE
Move Gamma to math.obl

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#181]
I missed `Gamma` on my previous issue! https://github.com/objeck/objeck-lang/issues/171

**Comment by objeck** [comment]
Please provide "someone" a list of functions for ``math.obl``. Note, if the functions are moved outside of ``lang.obl`` syntax such as ``a->Pow(3)`` will be reduced to ``Float->Power(2, 3)``.

**Comment by hgntn** [comment]
`Float->Gamma`, `Float->Factorial`, `Float->DoubleFactorial`. I think it's acceptable. These are of advanced mathematics, not what you are learning and using at school.

**Comment by objeck** [comment]
``Float->Gamma`` cannot be moved.

**Comment by hgntn** [comment]
> `Float->Gamma` cannot be moved.

OK.
