### ISSUE TITLE
Rename Ceiling to Ceil

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#183]
I think if you decided to rename `Power` to `Pow` then it's natural to rename `Ceiling` to `Ceil`.

**Comment by hgntn** [comment]
> Done, but really?

On C/C++/Java the function's name is Ceil.

**Comment by objeck** [comment]
My goal is not to rewrite C to C++ to Java/D to Python

**Comment by iahung** [comment]
> > Done, but really?
> 
> On C/C++/Java the function's name is Ceil.

On the .NET world, it's named Ceiling. On Excel it's also Ceiling.
