### ISSUE TITLE
Objeck REPL Shell

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#184]
### Discussed in https://github.com/objeck/objeck-lang/discussions/157

<div type='discussions-op-text'>

<sup>Originally posted by **tn1997tn** February 16, 2023</sup>
What do you think about it?</div>

Very useful when you need to execute single line of code like `2.0->Pow(3.0)` without having to put it in a source file, compile and run the traditional way!

**Comment by objeck** [comment]
Good idea, will give it some thought

**Comment by objeck** [comment]
I will create a project for this. GTK support is interesting but needs to be more compelling, as I prefer web-based UIs.

**Comment by objeck** [comment]
Thoughts on the REPL editor?

**Comment by objeck** [comment]
Ok, I do this...

**Comment by objeck** [comment]
Ok, I will delivery this

**Comment by objeck** [comment]
Ok, all the piece parts are available to create this, namely the debugger and LSP server; however, I need more time to implement this. I can help if someone in the community can pick this up.
