### ISSUE TITLE
Add Complex class to handle complex numbers

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#185]
### Discussed in https://github.com/objeck/objeck-lang/discussions/126

<div type='discussions-op-text'>

<sup>Originally posted by **PHdrr** February  3, 2023</sup>
You could use C++'s std::complex as a reference:

https://en.cppreference.com/w/cpp/numeric/complex</div>

**Comment by objeck** [comment]
Looking to find someone to write this...
