### ISSUE TITLE
Extend Pow function

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#186]
After https://github.com/objeck/objeck-lang/issues/177 is resolved `2->Pow(3)` is possible now. But what about `2.0->Pow(3)` or `2->Pow(3.0)`? IMO, the Pow function should be overloaded so that if either the power base or the power to raise is a Float then the output will be a Float. If both of them are integer typed then the output should be an Int.

**Comment by hgntn** [comment]
The implementation of `Pow(Float, Int)` and `Pow(Int, Float)` seems fine. But about `Pow(Int, Int) ~ Int`, isn't `Float->Pow(r->As(Float), r->As(Float))` is still a `Float`? What about `Float->Pow(r->As(Float), r->As(Float))->As(Int)`?

**Comment by objeck** [comment]
Thank you, I noticed that it is incorrect. I wIll fix it tonight.

**Comment by objeck** [comment]
Fixed
