### ISSUE TITLE
Equivalent to for loop

### ISSUE THREAD

**Issue by PHdrr** [objeck/objeck-lang#190]
`3.times |i| { i->PrintLine(); }`

is equivalent to `for(i := 0; i < 3; i++) { i->PrintLine(); }`

**Comment by objeck** [comment]
There already is 'each(i : 3)'. Your suggestion could be implemented in the parser are you able to submit the changes?

**Comment by PHdrr** [comment]
> There already is `each(i : 3) { i->PrintLine(); }`.

I don't know this is possible!
