### ISSUE TITLE
Extend math functions to allow taking input of integer types

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#195]
Currently various math functions only allowed to take input of float type. On other languages, there is no such limitation. If an integer typed value is detected it will be automatically casted to float type and fed to the math functions.

**Comment by objeck** [comment]
Correct, the model is based on standard C, assuming one can cast inputs and outputs ints.

**Comment by iahung** [comment]
> Correct, the model is based on standard C, assuming one can cast inputs and outputs to ints.

Excuse me please but I think Objeck should be compared to C++ instead of C, isn't it? What's the point of supporting function overloading if you don't use it on your standard library? On C++, sqrt(2) and pow(2,3) are fine.

**Comment by PHdrr** [comment]
On Fantom, it's the same. Many math functions are only available for Float type:

https://fantom.org/doc/sys/Int

https://fantom.org/doc/sys/Float

https://fantom.org/doc/sys/Decimal

Note: Fantom's Decimal is BigDecimal in Java and System.Decimal in .NET. Like Objeck, Int and Float of Fantom are 64-bit.

**Comment by objeck** [comment]
Point taken for ease of use. I will look into this.

**Comment by iahung** [comment]
> Point taken for ease of use. I will look into this.

After reading the Fantom docs, I think it's not much to write 2.0 instead of 2. This is the reason why I closed this issue :smile:

**Comment by objeck** [comment]
Agree, the library change to support ``Int`` is just a cast. Let me go ahead and explore this more. Cases that mix Int and Float will require more inspection.

**Comment by objeck** [comment]
The update to ``Sqrt`` was three cut/paste lines of code. I will review the Float class before the next release and update the Int class accordingly.

**Comment by objeck** [comment]
Thanks, it is a very specific use case for on font family. For other shells, I do need to code down to this level.

```
cfi.cbSize = sizeof(CONSOLE_FONT_INFOEX);
cfi.nFont = 0;
cfi.dwFontSize.X = 8;
cfi.dwFontSize.Y = 16;
cfi.FontFamily = FF_SIMHEI;
cfi.FontWeight = FW_NORMAL;
wcscpy(cfi.FaceName, L"SimHei");
```

**Comment by objeck** [comment]
I need to figure out what else to add to the Int class, as trig functions are bounded. I am close to this and assume folks can cast Ints to Floats as needed.
