### ISSUE TITLE
Type inference got it wrong?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#197]
Have a look at this code:

```
class Test {
	function : Main(args : String[]) ~ Nil {
		foo := 1.0;
        	bar := foo;
        	bar->PrintLine();
	}
}
```

`bar` should be of type `Float` the same as `foo`? No, `bar` was automatically casted to `Int`. This is the reason why this code will print 1 and not 1.0.

**Comment by iahung** [comment]
Even casting to Float like this doesn't work: `bar := foo->As(Float);`

**Comment by iahung** [comment]
Objeck can't write the normal style `Float bar := foo;`? Why do you said it's multi-paradigm?

**Comment by iahung** [comment]
It seems bar is correctly detected as Float when I hovering mouse over it. So the problem is of PrintLine. I tried to change `foo := 1.1` and this time it works as expected. So, PrintLine will print number like 1.0 as 1. This is the wrong behavior IMO.

**Comment by objeck** [comment]
It is the default behavior for ``wcout`` when passed a double value of ``1.0``. There are ways to adjust the ``Float`` precision and format (i.e., fixed, scientific, and hex).

**Comment by iahung** [comment]
> There are ways to adjust the `Float` precision and format (i.e., fixed, scientific, and hex).

How to do that?
