### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#202]
```
class Test {
	function : Main(args : String[]) ~ Nil {
		Brun();
	}

	function : native : Brun() ~ Nil {
		sum := 0;
		N := 2147483647;
		for(i := 1; i < N; i++) {
			sum += i->Sqrt();
		}
		sum->PrintLine();
	}
}
```

The same code on C# is much faster. I used PowerShell's Measure-Command, the C# program took less than a minute but the Objeck program took about 32 minutes to complete.

**Comment by objeck** [comment]
In short, I forgot to add/update some function signatures for inlining primitive function calls. Because the signatures needed to be updated, the optimization broke down. 

More detail...

After updating the signatures, your sample code above went from ``Before`` to ``After``. There are more instructions in the ``After`` code; however, function calls like ``Int->Sqrt()`` are inlined to ``Float->Sqrt()`` + ``Float->Round()``. Those functions are decomposed by the JIT compiler into 2 Intel instructions.

If you ever want to inspect the generated bytecode, run the compiler with the ``-asm`` option at the end of the compile command.

Before
```
0:	LOAD_INT_LIT: value=0
1:	STOR_INT_VAR: id=0; local=true
2:	LOAD_INT_LIT: value=2147483647
3:	STOR_INT_VAR: id=1; local=true
4:	LOAD_INT_LIT: value=1
5:	STOR_INT_VAR: id=2; local=true
6:	LBL
7:	LOAD_INT_VAR: id=1; local=true
8:	LOAD_INT_VAR: id=2; local=true
9:	LES_INT
10:	JMP: index=24, conditional=false
11:	LOAD_INT_VAR: id=2; local=true
12:	LOAD_INST_MEM
13:	MTHD_CALL: method='System.$Int:Sqrt:i,'; native=false
14:	LOAD_INT_VAR: id=0; local=true
15:	ADD_INT
16:	STOR_INT_VAR: id=0; local=true
17:	LBL
18:	LOAD_INT_LIT: value=1
19:	LOAD_INT_VAR: id=2; local=true
20:	ADD_INT
21:	STOR_INT_VAR: id=2; local=true
22:	JMP: index=7
23:	LBL
24:	LOAD_INT_VAR: id=0; local=true
25:	LOAD_INST_MEM
26:	MTHD_CALL: method='System.$Int:PrintLine:i,'; native=false
27:	RTRN
```
After
```
0:	LOAD_INT_LIT: value=0
1:	STOR_INT_VAR: id=0; local=true
2:	LOAD_INT_LIT: value=2147483647
3:	STOR_INT_VAR: id=1; local=true
4:	LOAD_INT_LIT: value=1
5:	STOR_INT_VAR: id=2; local=true
6:	LBL
7:	LOAD_INT_VAR: id=1; local=true
8:	LOAD_INT_VAR: id=2; local=true
9:	LES_INT
10:	JMP: index=38, conditional=false
11:	LOAD_INT_VAR: id=2; local=true
12:	LOAD_INST_MEM
13:	STOR_INT_VAR: id=3; local=true
14:	STOR_INT_VAR: id=4; local=true
15:	LOAD_INT_VAR: id=4; local=true
16:	I2F
17:	LOAD_INT_VAR: id=3; local=true
18:	STOR_INT_VAR: id=5; local=true
19:	STOR_FLOAT_VAR: id=6; local=true
20:	LOAD_FLOAT_VAR: id=6; local=true
21:	SQRT_FLOAT
22:	LOAD_INT_VAR: id=3; local=true
23:	STOR_INT_VAR: id=7; local=true
24:	STOR_FLOAT_VAR: id=8; local=true
25:	LOAD_FLOAT_VAR: id=8; local=true
26:	ROUND_FLOAT
27:	F2I
28:	LOAD_INT_VAR: id=0; local=true
29:	ADD_INT
30:	STOR_INT_VAR: id=0; local=true
31:	LBL
32:	LOAD_INT_LIT: value=1
33:	LOAD_INT_VAR: id=2; local=true
34:	ADD_INT
35:	STOR_INT_VAR: id=2; local=true
36:	JMP: index=7
37:	LBL
38:	LOAD_INT_VAR: id=0; local=true
39:	LOAD_INST_MEM
40:	MTHD_CALL: method='System.$Int:PrintLine:i,'; native=false
41:	RTRN
```

**Comment by iahung** [comment]
Too bad, I don't understand anything. But I will build the latest code to see if the bug was fixed or not.

**Comment by objeck** [comment]
> Too bad, I don't understand anything. But I will build the latest code to see if the bug was fixed or not.

No worries, in short, might be able to speed up ``Float->Sqrt()`` and ``Float->Round()``. 

Ticket notes: For ARM64, (macOS and Linux), look at ``FSQRT`` and ``FCVTZS``. For AMD64, ``ROUNDSD`` and ``SQRTSD``.

**Comment by iahung** [comment]
Confirm the bug was fixed.

**Comment by iahung** [comment]
> > Too bad, I don't understand anything. But I will build the latest code to see if the bug was fixed or not.
> 
> No worries, in short, might be able to speed up `Float->Sqrt()` and `Float->Round()`.
> 
> Ticket notes: For ARM64, (macOS and Linux), look at `FSQRT` and `FCVTZS`. For AMD64, `ROUNDSD` and `SQRTSD`.

Still don't understand 😄

**Comment by iahung** [comment]
@objeck Please check if `Float->Abs()` is inlined or not. Code using `Float->Abs()` is still slow.

**Comment by objeck** [comment]
@iahung, I remembered this. 

The ``Abs`` functions are written in Objeck in ``lang.obl`` and are inlined; however, the ``Abs`` operations could be reduced to single bytecode and target instructions for ARM64 and AMD64. I am still determining if I am going to make this update. Time is required to add two new bytecode instructions that are JIT mapped to 4 machine code instructions across targets. 

Implementation notes: AMD64 ``PABSD``(SSSE3) for ARM64 ``FABS``
