### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#207]
```
class Test {
	function : Main(args : String[]) ~ Nil {
		Brun();
	}

	function : native : Brun() ~ Nil {
		cprev := 3.0;
		cnext := 0.0;
		min := cprev;
		N := 2147483647;
		for(i := 1; i < N; i++) {
			cnext := cprev->Sin();
			if(cnext->Abs() < min) {
				min := cnext->Abs();
			}
			cprev := cnext;
		}
		min->PrintLine();
	}
}
```

This is the bottle neck:

```
			if(cnext->Abs() < min) {
				min := cnext->Abs();
			}
```

With these lines commented out, the program is very fast. The same code on C# doesn't have any performance problems.

**Comment by objeck** [comment]
Try the the latest code

**Comment by iahung** [comment]
> Try the the latest code

Already tried the latest code. The time shortened from 32 minutes to 10 minutes, still much slower than C# (less than a minute). Please test the code above and you will see.

**Comment by iahung** [comment]
@objeck This code is different from the previous code. I don't understand low level stuff, but I think I found the bottle neck. Please have a look. Thank you.

**Comment by objeck** [comment]
In short ``Abs`` can, and is, inlined only once. I will take a note to look at inline rules this week.

**Comment by iahung** [comment]
> In short `Abs` can, and is, inlined only once. I will take a note to look at inline rules this week.

Confirm that it is fixed in the latest code.

**Comment by objeck** [comment]
The code should be inlned

**Comment by iahung** [comment]
After commit https://github.com/objeck/objeck-lang/commit/05a0ad19d348c2e48ff58e4e58cd15d5ae59a63a it's on par with C#
