### ISSUE TITLE
All numberic types are 64 bit on Objeck?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#208]
If Int is 64 bit then the maximum value for an Int is 9223372036854775807 isn't it?

https://learn.microsoft.com/vi-vn/cpp/cpp/data-type-ranges?view=msvc-160

But this piece of code doesn't agree with it:

```
N := 9223372036854775807;
(N-1)->PrintLine();
```

It printed 2147483646. This mean the maximum value for an Int on Objeck is 2147483647 so Objeck's Int is 32 bit.

**Comment by iahung** [comment]
> For Win64, longs are 32-bit;

Yep, but Windows also provides `long long` which is 64 bit. Objeck is kind of like Java, why don't you learn from Java? Java's long is 64 bit regardless of the platforms. What's the point of compiling to bytecode and running on a VM if you don't care about being platform independent at all?

**Comment by objeck** [comment]
@iahung a type can be enforced via the following ``a : Int := 'h';`` the character will be treated as an ``Int``. The issue is not "learning" from Java. It is changing a 64-bit Windows environment to operate like a Posix 64 environment. Lots of minor changes to system APIs that operate on ``long`` to ensure they are operating ``int64_t`` on Windows. A lot of APIs to check between the compiler and VM. I may check a branch and explore further.

**Comment by objeck** [comment]
> > @iahung a type can be enforced via the following `a : Int := 'h';` the character will be treated as an `Int`.
> 
> Add it to document please? Otherwise who could know about that other than you?

I think it's [here](https://www.objeck.org/getting_started.html#lits_vars)

**Comment by objeck** [comment]
Point taken, I will take action to explore changing the 64-Windows model to be POSIX 64 compliant.

**Comment by iahung** [comment]
> > > @iahung a type can be enforced via the following `a : Int := 'h';` the character will be treated as an `Int`.
> > 
> > 
> > Add it to document please? Otherwise who could know about that other than you?
> 
> I think it's [here](https://www.objeck.org/getting_started.html#lits_vars)

Just another weird syntax @objeck:

```
a, b : Float := 13.5;
b += -a * 13;
"{$b}"->PrintLine();
```

In this case, both `a` and `b` were assigned to 13.5 or only `a` and `b` is undefined?

If `b` is undefined how could you add `-a * 13` to it? So `b` must be auto initialized to 0 somehow?
