### ISSUE TITLE
Unable to build 2d_game_13.obs example

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#210]
obc -src 2d_game_13.obs -lib gen_collect,sdl_game,sdl2 -dest 2d_game_13.obe

Error: Unable to resolve external library class: 'Data.JSON.JsonParser'; check library path

**Comment by objeck** [comment]
obc -src 2d_game_13.obs -lib gen_collect,sdl_game,sdl2,json -dest 2d_game_13.obe
