### ISSUE TITLE
Introduce the new keyword "in" to fix previous ugly syntax

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#211]
I believe you didn't learn from other programming languages and designed Objeck from scratch yourself, @objeck. Because if you did learn from other programming languages, you will not come up with such ugly and illogical syntax from the beginning.

On the context of `foreach`, the colon means "in". Only on Objeck, the colon means something completely different:

`each(i : arr)` on Objeck is equivalent to `for(i := 1; i < arr->Size(); i++)`

`i` is the index but not the element itself.

People reported this illogical syntax and you introduced just another even more illogical syntax:

`each( i := arr)`

Why `:=`? We are assigning `i` to something? `:=` should be reserved for assigning only!

We are assigning `i` to `arr` so `i` now is an array?

Recently, I know an even more illogical syntax from https://github.com/objeck/objeck-lang/issues/190

`each(i : 3) { i->PrintLine(); }`

What? As I said, the colon means "in". So `i` is in 3. What the heck does that mean?

Indeed, the meaning of 3 on this context is the range 0..3. But, why don't write `each(i : 0..3) { i->PrintLine(); }` to be more clear?

My workaround: it's obviously the colon doesn't mean "in" on the context for `foreach` as it should be on Objeck. So, to keep the original syntax `each( i : arr)` and it meanings (assumed many code is already using it), the best solution is introducing the keyword "in". So `each( i := arr)` will be `each( i in arr)` and `each(i : 3) { i->PrintLine(); }` will be `each(i in 0..3) { i->PrintLine(); }` (please remove the `i` in 3 syntax `each(i : 3) { i->PrintLine(); }` as it's too ugly, what's wrong with explicitly specifying a range? Does Objeck support range after all? If not, why don't just add it?).

**Comment by objeck** [comment]
I'm sorry that the syntax is ugly and my efforts illogical.

**Comment by objeck** [comment]
@iahung  I have looked at [Pascal](https://www.tutorialspoint.com/pascal/pascal_for_do_loop.htm), [Ruby](https://www.rubyguides.com/ruby-tutorial/loops/#:~:text=method%20in%20Ruby!-,The%20Ruby%20Each%20Loop,a%20range%20or%20a%20hash.), [Python](https://www.w3schools.com/python/python_for_loops.asp) and the C languages. Objeck's implementation is not more confusing than theirs, in my opinion.

I agree maybe ``each(a := array)`` is confusing; however, it is supported to indicate that the variable ``a`` is assigned to the indexed array element in ``array``. That ``a`` can be used like any other assigned variable.

**Comment by iahung** [comment]
Note: the article you linked for Pascal is wrong @objeck, it's the normal for loop. Foreach is here:

https://engineertips.wordpress.com/2020/04/26/delphi-foreach/

You could see, both Pascal (Delphi to be clear as Pascal was dead) and Python use "in".
