### ISSUE TITLE
Does Objeck has the concept of friend classes and functions?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#213]
@objeck You said if you moved Gamma, Factorial and friends from lang.obl then it will be no longer possible to use the syntax number->Gamma() anymore. This make me wonder if Objeck has the concept of friend classes and functions like C++?

p/s: I just read about C++'s friend classes and functions and I don't understand much about them but I think they could be the solution to have Gamma, Factorial and friends moved out of lang.obl but still able to use the syntax number->Gamma(). Please correct me if I was wrong, I'm not a programmer after all. Thank you.

**Comment by objeck** [comment]
It does not. The effort vs. the utility of implementing ``friend`` classes/functions is too high. I have been programming for a while and have only used the ``friend``C++ keyword a handful of times in edge cases. Java and C# do not directly support ``friend`` classes, and I personally think it is a dated C++feature.

**Comment by iahung** [comment]
> It does not. The effort vs. the utility of implementing `friend` classes/functions is too high. I have been programming for a while and have only used the `friend`C++ keyword a handful of times in edge cases. Java and C# do not directly support `friend` classes, and I personally think it is a dated C++ feature.

Is there a workaround to have Gamma, Factorial and friends moved out of lang.obl but still able to use the syntax number->Gamma()?
