### ISSUE TITLE
How to build without JIT support?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [objeck/objeck-lang#216]

**Comment by objeck** [comment]
Add the pre-processor _NO_JIT

**Comment by 2dpdlja496or43iq** [comment]
> Add the pre-processor _NO_JIT

Add to which Makefiles?

**Comment by objeck** [comment]
Under core/vm/make

**Comment by 2dpdlja496or43iq** [comment]
> Under core/vm/make

Only this file? https://github.com/objeck/objeck-lang/blob/master/core/vm/make/Makefile.msys2-clang.amd64

Do I need to add to https://github.com/objeck/objeck-lang/blob/master/core/vm/make/Makefile.msys2-clang.amd64.obd too?

**Comment by objeck** [comment]
Only the first, the second makefile is for the debugger. If you look at the make files under the debugger directory, core/debugger/make you will see the option to disable the JIT compiler in use.

**Comment by 2dpdlja496or43iq** [comment]
> Only the first, the second makefile is for the debugger. If you look at the makefiles under the debugger directory, core/debugger/make you will see the option to disable the JIT compiler in use.

OK.
