### ISSUE TITLE
Failed to create portable runtime if Objeck was built with MSYS2

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#222]
### Discussed in https://github.com/objeck/objeck-lang/discussions/221

<div type='discussions-op-text'>

<sup>Originally posted by **iahung** April 28, 2023</sup>
Followed the guide to great a portable runtime.

`obb -src_file test.obe -to_dir test -to_name test`

Well, always said `>>> Invalid Objeck install directory: '' <<<`.

I have to feed the Objeck directory to it:

`obb -src_file test.obe -to_dir test -to_name test -install C:\objeck-lang`

```
>>> Error encounented build native runtime environment <<<
        filesystem error: cannot create directory: No such file or directory [test\test]
```

So, it doesn't automatically create the `test` directory for me.

I decided to create that directory manually. Then:

```
>>> Error encounented build native runtime environment <<<
        filesystem error: cannot copy: File exists [C:\objeck-lang\bin] [C:\test\test\runtime\bin]
```

I started to lost patient. I run the command again:

`>>> Target directory 'test\test' already exists <<<`

I decided to stop trying.</div>

**Comment by objeck** [comment]
Which compiler was used? MSYS2 can change Windows path names for some APIs. I need to know what to test against.

**Comment by iahung** [comment]
> Which compiler was used? MSYS2 can change Windows path names for some APIs. I need to know what to test against.

Both UCRT64 and CLANG64.

**Comment by iahung** [comment]
Confirmed there is the same problem when running on the MSYS2 Shell.

**Comment by iahung** [comment]
@objeck Is there any progress on this?

**Comment by objeck** [comment]
> The issue is that the MSYS2 implementations of the C++17 filesystem libraries behave differently than they do on macOS, Linux, and Windows via VS. The `copy` API complains directories exist; however, I am passing the `overwrite_existing` flag to the API. The `exists` function returns `0` when valid Windows file names are passed.
> 
> Will have to explore workarounds.

BTW - The code is pretty easy to follow. It is creating directories, copy files, renaming files, deleting files, and creating a file.

**Comment by objeck** [comment]
After researching this issue, the problem is related to calling ``_spawnve`` (Win32) or ``execve`` (Posix) under MSYS2 to spawn a new Windows process. This system call has a known [bug](https://github.com/xpack-dev-tools/ms-spawn-issue) under MSYS2. Commit [716d811](https://github.com/objeck/objeck-lang/commit/716d8116ebd9b7aa1affda35aa4424605de16cb0) should fix it.

**Comment by objeck** [comment]
Fixed, available for MSYS2 pulls and builds
