### ISSUE TITLE
Support AOT compilation

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#225]
Objeck without JIT is extremely slow. There are platforms don't allow JIT like Android and iOS where AOT is something must have for performance. Yes, I know Android and iOS are currently not supported. But AOT is something useful anyway. There are two kind of AOT: partial AOT like Java, Mono,... and full AOT like .NET's NativeAOT. I don't know which kind of AOT you would choose to implement though.

**Comment by objeck** [comment]
Yes, an AOT can be written for the language. The issue with iOS and Android is buffer execution.

**Comment by iahung** [comment]
> The issue with iOS and Android is buffer execution.

Please explain more. I don't understand.

**Comment by objeck** [comment]
An AOT compiler can generate machine code ahead of time; however, it must be loaded for execution. It appears both iOS and Android support JITs. With the introduction of Apple silicon, macOS was hardened, [code and policy](https://github.com/objeck/objeck-lang/tree/master/core/vm/arch/jit/arm64) are required to enable JIT support.

**Comment by iahung** [comment]
https://pojavlauncherteam.github.io/JIT.html#what-is-jit-and-why-do-i-care

**Comment by iahung** [comment]
> An AOT compiler can generate machine code ahead of time; however, it must be loaded for execution. It appears both iOS and Android support JITs. With the introduction of Apple silicon, macOS was hardened, [code and policy](https://github.com/objeck/objeck-lang/tree/master/core/vm/arch/jit/arm64) are required to enable JIT support.

My information regarding iOS and Android is outdated. Sorry.
