### ISSUE TITLE
Extend Objeck compiler to support compiling to JavaScript

### ISSUE THREAD

**Issue by PHdrr** [objeck/objeck-lang#227]
WebAssembly in it current form is not a viable target to compile to because it doesn't support garbage collector. Objeck is a GC-ed language so a garbage collector is definitely needed. JavaScript VMs like the browsers and NodeJS on the other hands are much more powerful and all have a working garbage collector.

**Comment by objeck** [comment]
I would target WebAssembly. One can create a WebAssembly-friendly GC. Retargeting the language for WebAsm, MSIL, or the JVM is an effort. The project started because of my interest in VMs; the compiler and debugger frontends were added later.
