### ISSUE TITLE
Offer a plain C interface to allow developing Objeck plugins using any languages could output a native C-compatible DLL

### ISSUE THREAD

**Issue by PHdrr** [objeck/objeck-lang#230]
Current interface is C++ only thus limiting Objeck plugins to be written in C++ only. The Objeck plugins system uses dynamic load of DLL using GetProcAddress on Windows and dlsym on Unix, so the only requirement for the DLL is it's C-compatible (the symbols are not decorated so it's possible to call from plain C.).

**Comment by objeck** [comment]
Good suggestion. The only C++ dependency that I am aware of is std::(w)string. The signatures can easily be changed to wchar_t* or char*. The context object passed into C functions is a struct.

**Comment by iahung** [comment]
> Good suggestion. The only C++ dependency that I am aware of is std::(w)string. The signatures can easily be changed to wchar_t* or char*. The context object passed into C functions is a struct.

I think the OP's suggestion is to provide a plain C wrapper for the current C++ based interface and not about replacing the current C++ based interface with a plain C interface @objeck
