### ISSUE TITLE
Support compiling of Objeck using Emscripten

### ISSUE THREAD

**Issue by PHdrr** [objeck/objeck-lang#231]
This will help running programs written in Objeck on the browsers without having the Objeck compiler able to generate JavaScript or WebAssembly output as it will compile the whole Objeck VM to WebAssembly (or JavaScript for browsers don't support WebAssembly). In short, it brings the whole Objeck VM to the web.

**Comment by objeck** [comment]
> This will help running programs written in Objeck on the browsers without having the Objeck compiler able to generate JavaScript or WebAssembly output as it will compile the whole Objeck VM to WebAssembly (or JavaScript for browsers don't support WebAssembly). In short, it brings the whole Objeck VM to the web.

Thanks, I came across this the other day. I will look into this further.
