### ISSUE TITLE
More information about concurrency on Objeck

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#234]
The section for `Threads` on `Getting Started` is too short. Please provide more information and more examples, preferably complete programs (currently it's only a snippet of code).

https://objeck.org/getting_started.html#threads

**Comment by objeck** [comment]
Thanks, checkout this [example](https://github.com/objeck/objeck-lang/blob/master/programs/deploy/threads_6.obs). I will add it to the documentation.
