### ISSUE TITLE
ADTs

### ISSUE THREAD

**Issue by Stonygeist123** [objeck/objeck-lang#238]
Adding Rust-like ADTs and pattern matching would be pretty useful since it makes coding more elegant and easier

**Comment by objeck** [comment]
@Stonygeist123 Thanks for the suggestion; I will look into it. By AST you mean algebraic vs. abstract data types?

**Comment by objeck** [comment]
Should be able to provide TypeScript-level support by extending the ``alias`` keyword to include type unions.

**Comment by Stonygeist123** [comment]
@objeck Both, algebraic and abstract data types would be neat. Though I am not sure if a class like in C++ would be better than a TypeScript-like union syntax.

**Comment by objeck** [comment]
[Here's](https://github.com/objeck/objeck-lang/blob/master/programs/tests/prgm229.obs) an interface-based solution. I do not think I need to add anything new to the language.
