### ISSUE TITLE
Add a switch to obr to directly set OBJECK_STDIO mode

### ISSUE THREAD

**Issue by iahunq** [objeck/objeck-lang#240]
Without having to set the environment variable OBJECK_STDIO globally. I still have no idea how this switch would look like though. The reason for this suggestion is there are not many editors allowing setting environment variables internally like Sublime Text and wrapping obr command in batch script or shell script not always work (some editors really don't like this). Objeck-lsp needs OBJECK_STDIO set to stdio but normal command line program's output will be broken with OBJECK_STDIO set to stdio.

**Comment by objeck** [comment]
Thanks, will take a look at this

**Comment by objeck** [comment]
How about a config file?

**Comment by objeck** [comment]
Add now syntax will be `` --OBJECK_STDIO=binary prgm239.obe a b  c  d   e``

**Comment by objeck** [comment]
Added, will test and tweak
