### ISSUE TITLE
This code doesn't work!

### ISSUE THREAD

**Issue by iahunq** [objeck/objeck-lang#241]
Compiled, but doesn't work!

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		Brun();
	}

	function : native : Brun() ~ Nil {
		N : Int := 9223372036854775807;
		i : Int;
		for(i := 1; i < N; i++) {
			"Brun"->PrintLine();
		}
	}
}
```

You could see I tried to force the type Int, but it doesn't work either if you forced Int or not.

**Comment by iahunq** [comment]
Tried with N = 4294967295, doesn't work too. It will only work if N <= 2147483647.

**Comment by objeck** [comment]
Fixed. Old code left over from when the Windows runtime was 32-bit, and Linux/macOS was 64-bit. I looked across the code and did not find any other instances.

**Comment by iahunq** [comment]
> Fixed. Old code left over from when the Windows runtime was 32-bit, and Linux/macOS was 64-bit. I looked across the code and did not find any other instances.

What do you think about making a new release?
