### ISSUE TITLE
Adding examples to the API document

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#246]
I can't say I have read the whole API document, but from what I have read, I found there are no examples.

**Comment by objeck** [comment]
I will look into this for the next release. The documentation is auto-generated, so we must figure out how to add inline examples. Syntax highlighting would also be a welcome addtion.

**Comment by objeck** [comment]
I am looking at adding the [Prism](https://prismjs.com/) syntax highlighting library to the API documentation for code examples. Considering using Sourcegraph's Cody AI for documentation as it can "understand" and annotate Objeck code.

**Comment by objeck** [comment]
Below are trial run videos. I need to link the related code with the videos.

- Basics: https://youtu.be/Qj1n6NSfOqQ
- Data types: https://youtu.be/6jumPoRLXHQ

I will also post-edit the "real" videos once I finish creating the pipeline. Plan to write code to translate Objeck source into Prism-friendly HTML and Cody AI to describe what the code is doing.

**Comment by objeck** [comment]
Here's an [example](https://github.com/objeck/objeck-lang/blob/master/docs/images/inline_doc_mockup.png) of inline documentation. I plan to use the REPL shell to create examples. We still need to look into automating the process, so more to come.

**Comment by objeck** [comment]
Please refer to commit 9a54a6f66e983682238ad22822ea71b856fa0755. I will add more API code examples in upcoming releases.
