### ISSUE TITLE
Call Objeck from C++

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#247]
I don't know Quirrel either, but I think I know something similar: https://github.com/brwhale/KataScript. Except KataScript was designed from the beginning to be embedded into C++. The previous discussion was closed so I open a new one: https://github.com/objeck/objeck-lang/issues/219

My idea is something like reverse JNI, that is calling Java from C++ (instead of normal JNI, calling C++ from Java). Or it maybe something like Lua that could be embedded into C++ to provide scripting capacity, e.g: MPV used Lua to allow users writing plugins in Lua instead of C++.

Update: reverse JNI which calling Java from C++ is embed the JVM into the C++ application anyway. So the previous OP was right, it's about embed the Objeck VM into C++ application.

**Comment by objeck** [comment]
Interestingly enough, I plan to turn the compiler and runtime into single C++ classes. Most of that work has been completed as part of the REPL project. I will look into the above futher.

**Comment by objeck** [comment]
It is scheduled for the next major release, along with REPL shell support.

**Comment by objeck** [comment]
Refer to commit 94cfdd89d

**Comment by iahung** [comment]
How to use it then? I got many of undefined references errors.

**Comment by iahung** [comment]
My test code is as simple as this:

```
#include "lang.h"
#include <iostream>

int main(void) {
	std::wstring code = L"class Test1 {"
							"function : Main(args : String[]) ~ Nil {"
								"\"foo\"->PrintLine();"
							"}"
						"}";
	std::cout << ObjeckLang::Compile(code) << std::endl;
	return 0;
}
```

**Comment by objeck** [comment]
Ok, thanks. I think the only part is missing is capturing the output in string.

**Comment by iahung** [comment]
But how to resolve the undefined references errors?

**Comment by objeck** [comment]
Do you mean Erin supported by the compiler?

**Comment by iahung** [comment]
Don't understand. Btw, this is the error message:

```
$ g++ test.cpp -o test
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vfHvH.o:test.cpp:(.text+0xd53): undefined reference to `ObjeckLang::Compile(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vfHvH.o:test.cpp:(.rdata$.refptr.logger[.refptr.logger]+0x0): undefined reference to `logger'
collect2.exe: error: ld returned 1 exit status
```

If I add `lang.cpp` to the list, even more undefined references errors:

```
$ g++ test.cpp lang.cpp -o test
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cccJWa2U.o:test.cpp:(.rdata$.refptr.logger[.refptr.logger]+0x0): undefined reference to `logger'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xee2): undefined reference to `Parser::Parse()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xf5a): undefined reference to `ContextAnalyzer::Analyze()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xf8d): undefined reference to `IntermediateEmitter::Translate()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xfe9): undefined reference to `ItermediateOptimizer::ItermediateOptimizer(backend::IntermediateProgram*, int, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, bool, bool)'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x1004): undefined reference to `ItermediateOptimizer::Optimize()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x107a): undefined reference to `backend::FileEmitter::Get()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x12e5): undefined reference to `Loader::Load()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x132b): undefined reference to `Loader::GetProgram()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x134f): undefined reference to `Loader::GetProgram()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x1392): undefined reference to `Runtime::StackInterpreter::Execute(unsigned long long*, long*, long, StackMethod*, unsigned long long*, bool)'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN8frontend13ParsedProgramD1Ev[_ZN8frontend13ParsedProgramD1Ev]+0x73): undefined reference to `frontend::TreeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN6ParserC1ERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEbRSt6vectorISt4pairIS5_S5_ESaISA_EE[_ZN6ParserC1ERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEbRSt6vectorISt4pairIS5_S5_ESaISA_EE]+0xbe): undefined reference to `Parser::LoadErrorCodes()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x1f4): undefined reference to `frontend::TypeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x2b3): undefined reference to `frontend::TypeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x36f): undefined reference to `frontend::TypeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x449): undefined reference to `frontend::TypeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x52c): undefined reference to `frontend::TypeFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x60f): more undefined references to `frontend::TypeFactory::Instance()' follow
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7backend19IntermediateProgramD1Ev[_ZN7backend19IntermediateProgramD1Ev]+0x1f7): undefined reference to `backend::IntermediateFactory::Instance()'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7Runtime16StackInterpreterC1EP12StackProgram[_ZN7Runtime16StackInterpreterC1EP12StackProgram]+0x18): undefined reference to `Runtime::StackInterpreter::Initialize(StackProgram*)'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7Runtime16StackInterpreterC1EP12StackProgram[_ZN7Runtime16StackInterpreterC1EP12StackProgram]+0xc3): undefined reference to `MemoryManager::AddPdaMethodRoot(StackFrameMonitor*)'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7Runtime16StackInterpreter13intpr_threadsE[.refptr._ZN7Runtime16StackInterpreter13intpr_threadsE]+0x0): undefined reference to `Runtime::StackInterpreter::intpr_threads'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7Runtime16StackInterpreter16intpr_threads_csE[.refptr._ZN7Runtime16StackInterpreter16intpr_threads_csE]+0x0): undefined reference to `Runtime::StackInterpreter::intpr_threads_cs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN6Loader7programE[.refptr._ZN6Loader7programE]+0x0): undefined reference to `Loader::program'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN12StackProgram7prop_csE[.refptr._ZN12StackProgram7prop_csE]+0x0): undefined reference to `StackProgram::prop_cs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN12StackProgram10program_csE[.refptr._ZN12StackProgram10program_csE]+0x0): undefined reference to `StackProgram::program_cs'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7backend19IntermediateProgram8instanceE[.refptr._ZN7backend19IntermediateProgram8instanceE]+0x0): undefined reference to `backend::IntermediateProgram::instance'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7backend19IntermediateFactory8instanceE[.refptr._ZN7backend19IntermediateFactory8instanceE]+0x0): undefined reference to `backend::IntermediateFactory::instance'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN8frontend11TreeFactory8instanceE[.refptr._ZN8frontend11TreeFactory8instanceE]+0x0): undefined reference to `frontend::TreeFactory::instance'
collect2.exe: error: ld returned 1 exit status
```

**Comment by objeck** [comment]
> Don't understand. Btw, this is the error message:
> 
> 
> 
> ```
> 
> $ g++ test.cpp -o test
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vfHvH.o:test.cpp:(.text+0xd53): undefined reference to `ObjeckLang::Compile(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >)'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vfHvH.o:test.cpp:(.rdata$.refptr.logger[.refptr.logger]+0x0): undefined reference to `logger'
> 
> collect2.exe: error: ld returned 1 exit status
> 
> ```
> 
> 
> 
> If I add `lang.cpp` to the list, even more undefined references errors:
> 
> 
> 
> ```
> 
> $ g++ test.cpp lang.cpp -o test
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cccJWa2U.o:test.cpp:(.rdata$.refptr.logger[.refptr.logger]+0x0): undefined reference to `logger'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xee2): undefined reference to `Parser::Parse()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xf5a): undefined reference to `ContextAnalyzer::Analyze()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xf8d): undefined reference to `IntermediateEmitter::Translate()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0xfe9): undefined reference to `ItermediateOptimizer::ItermediateOptimizer(backend::IntermediateProgram*, int, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, bool, bool)'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x1004): undefined reference to `ItermediateOptimizer::Optimize()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x107a): undefined reference to `backend::FileEmitter::Get()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x12e5): undefined reference to `Loader::Load()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x132b): undefined reference to `Loader::GetProgram()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x134f): undefined reference to `Loader::GetProgram()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text+0x1392): undefined reference to `Runtime::StackInterpreter::Execute(unsigned long long*, long*, long, StackMethod*, unsigned long long*, bool)'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN8frontend13ParsedProgramD1Ev[_ZN8frontend13ParsedProgramD1Ev]+0x73): undefined reference to `frontend::TreeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN6ParserC1ERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEbRSt6vectorISt4pairIS5_S5_ESaISA_EE[_ZN6ParserC1ERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEbRSt6vectorISt4pairIS5_S5_ESaISA_EE]+0xbe): undefined reference to `Parser::LoadErrorCodes()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x1f4): undefined reference to `frontend::TypeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x2b3): undefined reference to `frontend::TypeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x36f): undefined reference to `frontend::TypeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x449): undefined reference to `frontend::TypeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x52c): undefined reference to `frontend::TypeFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb[_ZN15ContextAnalyzerC1EPN8frontend13ParsedProgramENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEb]+0x60f): more undefined references to `frontend::TypeFactory::Instance()' follow
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7backend19IntermediateProgramD1Ev[_ZN7backend19IntermediateProgramD1Ev]+0x1f7): undefined reference to `backend::IntermediateFactory::Instance()'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7Runtime16StackInterpreterC1EP12StackProgram[_ZN7Runtime16StackInterpreterC1EP12StackProgram]+0x18): undefined reference to `Runtime::StackInterpreter::Initialize(StackProgram*)'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.text$_ZN7Runtime16StackInterpreterC1EP12StackProgram[_ZN7Runtime16StackInterpreterC1EP12StackProgram]+0xc3): undefined reference to `MemoryManager::AddPdaMethodRoot(StackFrameMonitor*)'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7Runtime16StackInterpreter13intpr_threadsE[.refptr._ZN7Runtime16StackInterpreter13intpr_threadsE]+0x0): undefined reference to `Runtime::StackInterpreter::intpr_threads'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7Runtime16StackInterpreter16intpr_threads_csE[.refptr._ZN7Runtime16StackInterpreter16intpr_threads_csE]+0x0): undefined reference to `Runtime::StackInterpreter::intpr_threads_cs'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN6Loader7programE[.refptr._ZN6Loader7programE]+0x0): undefined reference to `Loader::program'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN12StackProgram7prop_csE[.refptr._ZN12StackProgram7prop_csE]+0x0): undefined reference to `StackProgram::prop_cs'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN12StackProgram10program_csE[.refptr._ZN12StackProgram10program_csE]+0x0): undefined reference to `StackProgram::program_cs'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7backend19IntermediateProgram8instanceE[.refptr._ZN7backend19IntermediateProgram8instanceE]+0x0): undefined reference to `backend::IntermediateProgram::instance'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN7backend19IntermediateFactory8instanceE[.refptr._ZN7backend19IntermediateFactory8instanceE]+0x0): undefined reference to `backend::IntermediateFactory::instance'
> 
> C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccyNHvrX.o:lang.cpp:(.rdata$.refptr._ZN8frontend11TreeFactory8instanceE[.refptr._ZN8frontend11TreeFactory8instanceE]+0x0): undefined reference to `frontend::TreeFactory::instance'
> 
> collect2.exe: error: ld returned 1 exit status
> 
> ```

Understand, the code currently needs to be built under visual studio 2022. When I create makefiles for the REPL project I will pull the above into a static library. May create a separate project to build the shared libraries (*.a, *.lib) and have the REPL project uses those libraries. The idea is in my head, just need to find a motivation to implement it :)

**Comment by objeck** [comment]
I was thinking something like the following as wrapper around the library.

```
auto compiler = Objeck::Compiler(sec);
if(compiler.Compile()) {
  auto output = Objeck::Runtime::Execute(compiler.GetCode());
  std::wcout << output << std::endl;
}
else {
  auto errors = compiler.GetErrors();
  for(auto &error : errors) {
    std::wcout << error << std::endl;
  }
}
```

**Comment by iahung** [comment]
Currently it seems to only support compiling and executing a whole source code (a complete content of a .obs file passed as `std::wstring`). What do you think about adding the ability to evaluate code snippets? I also think about an overloaded function to accept a whole .obs file (as the form of path to the .obs file on file system) as the input.

**Comment by objeck** [comment]
Let's first get something to work across targets. Then, iterate on the solution. 

My next goal is to get the REPEL code working in POSIX and MYSY2 environments.

**Comment by iahung** [comment]
So embedded Objeck will not have the ability to evaluate code snippets. What about adding overloaded methods to allow taking a .obs file as input for compile and a .obe file as input for execute?

**Comment by objeck** [comment]
Yes, the binary input is a .obl library file. The current solution is to support the new REPL component. It can be wrapped in the future to provide richer C++ support for things like the execution of single statements. Right now, I'm focused on getting the REPL finished.

**Comment by objeck** [comment]
Wrapped up macOS support, the general concept has been implemented across targets. We can iterate and add features as needed.
