### ISSUE TITLE
Add methods to handle hard links and symbolic links

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#248]
Luckily everything seems to be available on C++'s File System library:

https://en.cppreference.com/w/cpp/filesystem

**Comment by objeck** [comment]
Ok, I will look into it. 

Objeck uses the C++ 17 library when _it works_. The implementation is flaky at times. When it is, we use the native POSIX and Win32 equivalents.

**Comment by objeck** [comment]
Please, refer to the following https://github.com/sitewards/modman-php/issues/48. A design goal is not to implement OS-specific functionality. Thoughts?

**Comment by objeck** [comment]
Added in last commit

**Comment by iahung** [comment]
@objeck I have not yet tested the newly added methods. It seems I can't keep track of your commits. Btw, from the API doc, it seems you only added support for SymbolicLink but not HardLink, and the SymbolicLink class doesn't have methods to `UnLink` (safety delete the link without damaging the original file). The methods are also confusing. Why do we need to copy symbolic link with the `Copy` method? Why does the `Create` method must know whether the original file is a directory or a file by the third parameter?
