### ISSUE TITLE
This piece of code doesn't compile

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#250]
```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		(str + "bar")->PrintLine();
	}
}
```

So does this piece of code:

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		str->Append("bar")->PrintLine();
	}
}
```

**Comment by objeck** [comment]
Both return ``Nil``?

**Comment by iahung** [comment]
> Both return `Nil`?

What? I don't understand. Both `(str + "bar")` and `str->Append("bar")` should return a String, aren't them?

**Comment by objeck** [comment]
Append does not create a new string with each call; I thought it was inefficient. However, the platform has been optimized since the early days. Each call across the the line need to create a new object instance.

**Comment by iahung** [comment]
> Append does not create a new string with each call; I thought it was inefficient. However, the platform has been optimized since the early days. Each call across the the line need to create a new object instance.

OK. I understand.

**Comment by objeck** [comment]
Wait, maybe return ``@self`` as a builder, will try it.

**Comment by objeck** [comment]
Looking at the code we change the ``String->Append(..)`` methods to return ``@self`` for concatenation.

**Comment by iahung** [comment]
> Looking at the code we change the `String->Append(..)` methods to return `@self` for concatenation.

One side effect of this is we will have code like a chain like `A->B()->C()->...` that is normally seen on Java (and Fantom). It's something good or bad is up to debate 😄

**Comment by objeck** [comment]
Agreed, I will look into it. Originally, I did not want to take the performance hit.

**Comment by iahung** [comment]
Fantom took this approach to extreme. This is valid Fantom code: `2.plus(3).sqrt.toInt.plus(1).div(2)`. Yeah, Fantom has the JVM to back it. I'm totally fine with having to write an extra line on Objeck 😄

**Comment by iahung** [comment]
I only played a bit with Fantom so I'm in no way a Fantom expert. I recall on Fantom: `str := "foo";` then `str.plus("bar");` and `echo(str.plus("bar")); // will print "foobar"` don't change the value of `str`, to change the value of `str` you will have to use `str := str.plus("bar");`.

**Comment by iahung** [comment]
@objeck What is your final decision on this? You closed the issue without any updates.

**Comment by objeck** [comment]
No plans to change it at this time
