### ISSUE TITLE
Are you sure you really added `Directory->GetCurrent()`?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#252]
I build the latest git code from source on UCRT64. But when I compile test code I always see this error:

```
Undefined function/method call: 'GetCurrent(..)'
        Ensure the object and it's calling parameters are properly casted
```

@objeck Did you forget to upload the updated libraries?

**Comment by iahung** [comment]
Same for `Directory->SetCurrent()`

```
Undefined function/method call: 'SetCurrent(..)'
        Ensure the object and it's calling parameters are properly casted
```

**Comment by iahung** [comment]
`Directory->GetWorking()` and `Directory->SetWorking()` worked. It seems I can't keep track with your commits.

**Comment by objeck** [comment]
Nor can I at times...
