### ISSUE TITLE
Make it's possible to build objeck with MSVCRT (normal MSYS2 MINGW64)

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#255]
Currently it's required to use UCRT (UCRT64 or CLANG64 on MSYS2). But I found the only thing being `UCRT` on Objeck code base is `_dupenv_s`. Of course I'm not telling you to drop the modern UCRT function to use the old deprecated MSVCRT function but what about adding a macro to fall back to the legacy function `getenv` when manually added to makefiles, e.g: `-DMSYS2_MINGW64`?

Here you can see what I did to have Objeck built on MSYS2 MINGW64:

https://github.com/objeck/objeck-lang/commit/76ba3fba52865f94f49eb7917fe3e0a2adc03a5a

https://github.com/objeck/objeck-lang/commit/6350e15d5b71f744335a99dac6f0d91bfe0f0e92

Btw, I didn't add any macros like I'm describing above as I'm not good at coding (I changed the code to use only the legacy `getenv`).

**Comment by objeck** [comment]
Not sure I understand, ``getenv`` is [deprecated](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=msvc-170) in Windows, and the code compiles cleanly on MSYS2 UCRT64 and MSYS2 CLANG64. 

Is there another target that you suggest we support? If so, please submit the changes. I support three Windows build right now adding forth is too much.

**Comment by iahung** [comment]
> Not sure I understand, `getenv` is [deprecated](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=msvc-170) in Windows, and the code compiles cleanly on MSYS2 UCRT64 and MSYS2 CLANG64.
> 
> Is there another target that you suggest we support? If so, please submit the changes. I support three Windows build right now adding forth is too much.

Try building on MSYS2 MINGW64, you will see the compilation is fine but it failed at linking due to missing symbols related to `_dupenv_s`. My suggestion is add a macro called `MSYS2_MINGW64` and if that macro is defined (by manually editing makefiles to add `-DMSYS2_MINGW64`), the code will fall back to use `getenv`.

**Comment by objeck** [comment]
Ok, ``dupenv_s`` has been removed from all source code. If time permits, I will set up another MSYS2 shell. However, it is hard supporting all these Windows targets without help.

**Comment by iahung** [comment]
> Ok, `dupenv_s` has been removed from all source code. If time permits, I will set up another MSYS2 shell. However, it is hard supporting all these Windows targets without help.

No. Please don't do that! UCRT is the future. `dupenv_s` is what should be used, not `getenv`. Adding a macro to fallback to `getenv` is better than remove all `dupenv_s`!

**Comment by iahung** [comment]
Please rollback the commit that removed `_dupenv_s`. Since I know how to patch the source code to have it built on MSYS2 MINGW64, I will do this manually. It's only two source files affected.

**Comment by objeck** [comment]
> MSYS2 UCRT64 and MSYS2 CLANG64.

It was removed with the last release as the call is unsafe in Windows. The new code compiles cleanly with MSYS2 UCRT64 and MSYS2 CLANG64. Am I missing something? Is UCRT another target?

**Comment by iahung** [comment]
> > MSYS2 UCRT64 and MSYS2 CLANG64.
> 
> It was removed with the last release as the call is unsafe in Windows. The new code compiles cleanly with MSYS2 UCRT64 and MSYS2 CLANG64. Am I missing something? Is UCRT another target?

What did you replaced `_dupenv_s` with? `_dupenv_s` > `getenv_s` > `getenv`.

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/dupenv-s-wdupenv-s?view=msvc-170

UCRT is the new C runtime. MSVCRT is the legacy C runtime.

**Comment by iahung** [comment]
@objeck It seems you replaced `_dupenv_s` with `getenv_s`? It's OK. `getenv_s` is available on both UCRT and MSVCRT (at least on MSYS2). I didn't keep up with the latest changes in the code base. Sorry.

**Comment by objeck** [comment]
No problem. I was also confused about what you were asking. The calls to ``getenv_s``do not allocate memory from the heap, thus the code is cleaner when managing ``std::wstring`` allocation.

**Comment by iahung** [comment]
The latest code compiled cleanly without modifications on MSYS2 MINGW64.
