### ISSUE TITLE
Bundle name 'Collection.Generic' not defined in program or linked libraries

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#258]
Even if compiled with `-lib gen_collect`. Please have a look at your very `Getting Started` document:

https://objeck.org/getting_started.html#collect

p/s: latest version of Objeck

**Comment by objeck** [comment]
Builds cleanly, for me, under Linux x64, VS '22, MSYS2 Clang, and  MSYS2 UCRT. What am I missing.

**Comment by objeck** [comment]
Check your environment variables for the shell. Maybe OBJECK_LIB_PATH is being set for the build.

**Comment by iahung2** [comment]
`use Collection.Generic;` doesn't work, but `use Collection;` works.

**Comment by iahung2** [comment]
Tested with `echo %OBJECK_LIB_PATH%` on Windows Command Prompt and confirm that this environment variable is correctly set.

**Comment by objeck** [comment]
> `use Collection.Generic;` doesn't work, but `use Collection;` works.

Yes, ``Collection.Generic;`` was removed a while ago to support generics.

**Comment by iahung2** [comment]
> > `use Collection.Generic;` doesn't work, but `use Collection;` works.
> 
> Yes, `Collection.Generic` was removed a while ago to support generics.

What about updating `Getting Started` to match the latest changes?

**Comment by objeck** [comment]
Done, thank you!
