### ISSUE TITLE
Undefined function/method call: 'Find(..)'

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#259]
```
        Ensure the object and it's calling parameters are properly casted
        Possible alternative(s):
                method : public : Collection.Map->Find(K) ~ V
```

The code on your very `Getting Started` fails to compile:

https://objeck.org/getting_started.html#collect

```
area_codes := Map->New()<IntRef, String>;
area_codes->Insert(510, "Oakland");
area_codes->Insert(415, "San Francisco");
area_codes->Insert(650, "Palo Alto");
area_codes->Insert(408, "San Jose");
area_codes->Find(510)->PrintLine();
```

`Find()` is right there on API document: https://www.objeck.org/doc/api/collection-map_k-compare_v_.html#map-find

I wonder why the compiler can't see it?

**Comment by objeck** [comment]
What check-in are you using?

**Comment by objeck** [comment]
Refer to #258

**Comment by iahung2** [comment]
> Refer to #258

Btw, the error on this issue is not related to #258, though. There is a typo in my code:

`area_codes->Find("510")->PrintLine();`

The original code is `area_codes->Find(510)->PrintLine();`.

**Comment by objeck** [comment]
Ok, Oakland gets up early...
