### ISSUE TITLE
Rename System.IO.Filesystem to System.IO.FileSystem

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#260]

**Comment by objeck** [comment]
Thoughts https://en.wikipedia.org/wiki/File_system

**Comment by iahung2** [comment]
https://www.nuget.org/packages/System.IO.FileSystem/

**Comment by objeck** [comment]
Thanks going to pass on the upper case 'S'

**Comment by tqo50396** [comment]
> Thanks going to pass on the upper case 'S'

@objeck This is not the case. On latest release of Objeck, it's still `System.IO.Filesystem`.
