### ISSUE TITLE
How to iterate over a Map?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#261]

**Comment by objeck** [comment]
Try ``GetKeyValues()`` GetKeys()`` or ``GetValues()``, the first gives you a pair.

**Comment by iahung2** [comment]
> Try `GetKeyValues()`, `GetKeys()` or `GetValues()`, the first gives you a pair.

Please give me working examples. Btw, I think these examples should be on `Getting Started`.

**Comment by objeck** [comment]
https://github.com/objeck/objeck-lang/blob/master/programs/tests/prgm202.obs#L17

**Comment by objeck** [comment]
> > Try `GetKeyValues()`, `GetKeys()` or `GetValues()`, the first gives you a pair.
> 
> Please give me working examples. Btw, I think these examples should be on `Getting Started`.

Please propose the 'Getting Started' table of contents which you would like to see.

**Comment by iahung2** [comment]
> Please propose the 'Getting Started' table of contents you want to see.

There is no such a thing. But it's logical for you to tell how to iterate over them after you introduced them.

**Comment by iahung2** [comment]
> https://github.com/objeck/objeck-lang/blob/master/programs/tests/prgm202.obs#L17

My attempts failed because I only use `vector := map->GetKeyValues()`. I didn't add the `<Pair<String, String>>` part.

**Comment by iahung2** [comment]
Btw, this is `GetKeyValues()`. Please give the examples for `GetKeys()` and `GetValues()` too.
