### ISSUE TITLE
Some classes are there only to hold methods

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#262]
For example, this class:

https://www.objeck.org/doc/api/system.io.filesystem-filereaderwriter.html

After I created an object with `f := FileReaderWriter->New("README.md");`, I don't know what to do with it next. It turned out what I need is `FileReaderWriter->ReadFile("README.md");`.

**Comment by iahung2** [comment]
Btw, in my opinion methods are always associated with an object. These `methods` can be used without an object. They are better be called `functions`.

**Comment by objeck** [comment]
> `FileReaderWriter->ReadFile("README.md");`.

``FileReaderWriter->ReadFile("README.md");.`` is a function.

**Comment by iahung2** [comment]
> > `FileReaderWriter->ReadFile("README.md");`.
> 
> `FileReaderWriter->ReadFile("README.md");` is a function.

The point of this issue is, what to do with the object `f := FileReaderWriter->New("README.md");`? It's so useless that after you created it, you can do nothing with it. This is true not also with `FileReaderWriter` but also `FileReader` and `FileWriter`.

My opinion is if you gonna to use the class only as a functions holder like this, don't make a constructor. The default constructor (please correct me if I was wrong) is enough:

```
f := FileReaderWriter->New();
f->ReadFile("README.md");
```

Compared with the current implementation:

`f := FileReaderWriter->New("README.md");`

If you are the users, don't you expect you can do something with the object `f`? Like this?

```
f := FileReaderWriter->New("README.md");
f->ReadFile();
```

No, this will not gonna work as `ReadFile()` needs the file name as the argument. It doesn't use the file name of the object `f`.

Finally you will come up with something like this:

```
f := FileReaderWriter->New("README.md");
f->ReadFile("README.md");
```

So what is the point of creating an object `f` with file name specified? This file name is not used at all. Isn't an empty object `f` created with the default constructor is enough?

Please consider my suggestion @objeck

**Comment by objeck** [comment]
Thanks, @iahung2.

One can create an instance of ``FileReaderWriter`` to read lines, bytes, or buffers. Please see below. 

The ``FileReaderWriter->ReadFile("README.md")`` function is for convenience and reads a file into a ``String``. As with other object-oriented languages, one can call a class function from an instance such as ``f->ReadFile("README.md")`` or a class such as ``FileReaderWriter->ReadFile("README.md")``. I normally do the latter.

```
f := FileReaderWriter->New("README.md");
while(<>f->EoF()) {
  line := f->ReadLine();
  line->Size()->PrintLine();
};
f->Close();
```
