### ISSUE TITLE
A question about `String->Replace()`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#263]
It seems `String->Replace()` doesn't change the value of the string?

For example:

```
str := "example string";

str->Replace("example", "test");

str->PrintLine(); # still the original string

str := str->Replace("example", "test");

str->PrintLine(); # now it prints the changed string
```

Is it consistent with https://github.com/objeck/objeck-lang/issues/250?

**Comment by objeck** [comment]
Correct, it is immutable. It can be changed to modify the contents of the caller, thoughts?

**Comment by iahung2** [comment]
> Correct, it is immutable. It can be changed to modify the contents of the caller, thoughts?

Please have a look at this code:

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		str->Append("bar");
		str->PrintLine();
	}
}
```

If `str->Append()` could change the value of `str`, why can't `str->Replace()`?

Let we recall the failed to compile pieces of code on https://github.com/objeck/objeck-lang/issues/250:

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		(str + "bar")->PrintLine();
	}
}
```

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		str->Append("bar")->PrintLine();
	}
}
```

Then have a look at this code:

```
class Test1 {
	function : Main(args : String[]) ~ Nil {
		str := "foo";
		str->Replace("o", "a")->PrintLine();
	}
}
```

Surprisingly, it compiled just fine.

So my opinion is, there is nothing special about `str->Replace()`. If `str->Append()` doesn't return a new string, then so does `str->Replace()`. If you want to make `str->Replace()` return a new string, then you have to make `str->Append()` return a new string too.

**Comment by objeck** [comment]
Try
```
str += "bar";
str->PrintLine();
```

**Comment by iahung2** [comment]
> Try
> 
> ```
> str += "bar";
> str->PrintLine();
> ```
> 
> Append is called for the `+=` operator. I did not want it to return a new instance for performance reasons. Let me think more about your feedback.

Please don't misunderstand what I said. The only thing I said is that `str->Replace()` is not any more special than other methods, so if `str->Append()` doesn't return a new string, then `str->Replace()` shouldn't either.

**Comment by iahung2** [comment]
`str->ReplaceAll()` shouldn't return a new string, too.

**Comment by objeck** [comment]
Thanks for the feedback. I break operations into two categories. The first is, operations that add to an existing string in a predictable manner, like stream concatenation. The second, operations that modify a buffer in a more dynamic manner such as substring replacement. Concatenation is a common operation used frequently to build strings. Operations that 'may' modify all the contents of an should be a mutable in my opinion.

**Comment by iahung2** [comment]
> Thanks for the feedback. I break operations into two categories. The first is, operations that add to an existing string in a predictable manner, like stream concatenation. The second, operations that modify a buffer in a more dynamic manner such as substring replacement. Concatenation is a common operation used frequently to build strings. Operations that 'may' modify all the contents of an should be a mutable in my opinion.

Any of what you said have been added to the document yet? I don't see any changes on `Getting Started`. Btw, long story short, nothing changed?

**Comment by objeck** [comment]
Below are trial run videos. I need to link the related code with the videos.

- Basics: https://youtu.be/Qj1n6NSfOqQ
- Data types: https://youtu.be/6jumPoRLXHQ
