### ISSUE TITLE
[Suggestion] `-e` switch for `obi`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#265]
Inspired by scripting languages like `lua`, e.g: `lua -e 'print(1/3)'`

Should also work if pass via `stdin`, e.g: `echo 'print(1/3)' | lua`

**Comment by objeck** [comment]
Added ``-src`` switch in commit [8b8b7ee](https://github.com/objeck/objeck-lang/commit/8b8b7eedff4a936689941c0a68837a06a484838a). 

On Windows: ``obi -src "\"Hello World!\"->PrintLine()"``

**Comment by iahung2** [comment]
> Added `-src` switch in commit [8b8b7ee](https://github.com/objeck/objeck-lang/commit/8b8b7eedff4a936689941c0a68837a06a484838a).
> 
> On Windows: `obi -src "\"Hello World!\"->PrintLine()"`

What about `-lib`?

**Comment by objeck** [comment]
Done in commit [b52fe28](https://github.com/objeck/objeck-lang/commit/b52fe2833deb67b782e4474da46c2b2611693724)
