### ISSUE TITLE
[Suggestion] `obi` should be able to be used like an interpreter

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#266]
Feed whole source file to `obi` to run like script, e.g: `obi test.obs` and `cat test.obs | obi`.

**Comment by objeck** [comment]
I added an ``-open`` command line switch in commit 69fd01f2b

**Comment by iahung2** [comment]
> I added an `-open` command line switch in commit [69fd01f](https://github.com/objeck/objeck-lang/commit/69fd01f2b4746016a187fe7a00fb2db6e68aa7f6)

What about `-lib`?

**Comment by objeck** [comment]
Done in commit [b52fe28](https://github.com/objeck/objeck-lang/commit/b52fe2833deb67b782e4474da46c2b2611693724)
