### ISSUE TITLE
`obi -file` is freaking slow compared to `obr`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#269]
I built from the latest code with has JIT enabled by default. But from what I observed, it seems JIT doesn't work on `obi`.

**Comment by objeck** [comment]
Try updating the module makefile. I will check on this tomorrow.

**Comment by iahung2** [comment]
> Try updating the module makefile. I will check on this tomorrow.

The module makefile still has `-D_NO_JIT`.

**Comment by objeck** [comment]
Yes, remove that flag

**Comment by iahung2** [comment]
> Yes, remove that flag

That doesn't help.

**Comment by objeck** [comment]
The code generated using obi not optimized as to speed up the compile step. Also, the VM has cleanup to do after each run, where obr halts after each execution.

**Comment by iahung2** [comment]
> In lang.cop under module refer to line 51 try changing "s1" to "s3".

Worked.

**Comment by objeck** [comment]
Added as an option
