### ISSUE TITLE
[discussion] Procedural versions of `Print` and `PrintLine`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#272]
Same idea as #271. I think the procedural versions of `Print` and `PrintLine` could be put into the very same `cmath` module.

Update: If you think the users could confuse the OOP syntax with the procedural syntax, then I suggest the functions on the `cmath` module should have all lowercase names, like on C.

Update: If you decided that the functions on the `cmath` module should have all lowercase names then I suggest use `println` instead of `printline`; you could use `echo` if you liked.

**Comment by objeck** [comment]
Have you tried ``Standard->Print(1)->Print(',')->Print(2)->Print(',')->PrintLine(3);``?
