### ISSUE TITLE
[question] How to initialize an array directly?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#275]
On Objeck, it seems we have to create the array first, then add each of the elements manually. Is there a way to initialize the array directly, like on C?

https://en.cppreference.com/w/c/language/array_initialization

**Comment by objeck** [comment]
I will push out an update for bug #277 over the weekend. The issue was not found earlier as unit tests are run under Linux. I code mostly code in Windows and run regression under Linux x64.

**Comment by iahung2** [comment]
> Pull the latest code, as I found and resolved a bug.
> 
> Try for example
> 
> ```
> v1 := [1,2,3];
> v1->Size()->PrintLine();
> 
> v2 := ["one", "two", "three"];
> v2->Size()->PrintLine();
> ```

Both printed 3. Seems working as expected.
