### ISSUE TITLE
[question] How to initialize Collections directly?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#276]
Same problem with array on #275, it seems we have to create the Collection container first, then add each of the elements manually.

**Comment by objeck** [comment]
What are you trying to do? Please send a code example.

**Comment by iahung2** [comment]
> What are you trying to do? Please send a code example.

On modern Java and C#, you could initialize Collections with predefined values just like what you can do with an array directly without having to create it first and use methods to add each elements later; everything is done in one line. This is convenient but also somewhat make the languages more difficult to use since you will have to remember extra syntax (which brackets to use with which Collections). I want to discuss with you if it worth to add support for this on Objeck.

You could get the idea by searching on Google with `how to initialize Dictionary in Java`, `how to initialize Dictionary in C#` or `how to initialize map in C++`. Just replace `Dictionary` or `map` with the name of the Collections you want to search for. You will see there is syntax to both declare and initialize everything just in one line.

**Comment by objeck** [comment]
Without modifying the compiler, I added support for the following in commit [ccde224](https://github.com/objeck/objeck-lang/commit/ccde224e35b8b1ca0fc73ffd0d61abbbd81ae0ec):

```
elems := Collection.Vector->New(IntRef->FromArray([1,2,3]))<IntRef>;
elems->Size()->PrintLine();
```
