### ISSUE TITLE
[question] Is array an object on Objeck?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#279]
Or is it a primitive type? Could you add the `->ToString()` method and `->Print()` and `->PrintLine()` methods to array so we could print an array simply with `arr->PrintLine()`?

Update: On Java it needs to use `Arrays.toString()` method to correctly print the array to the screen, doing `arr.toString()` or `System.out.println(arr)` will print gibberish. I don't know how should we handle this on Objeck.

**Comment by objeck** [comment]
Kind of. There is a hidden array class that provides basic array support. It could be extended to provide ``Print()`` and ``PrintLine()`` functionality.

**Comment by objeck** [comment]
This feature has been added and tested.
