### ISSUE TITLE
Add `->ToString()` method to Collections

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#280]
So you could use something like Vector -> ToString() -> PrintLine().

Btw, what about adding `->Print()` and `->PrintLine()` method to Collections so we could print a vector's content to screen directly?

Vector -> Print()

Vector -> PrintLine()

**Comment by objeck** [comment]
Yes, if the generic collection type has a ``Print`` or ``PrintLine`` method. We will need to use introspection to check. Not hard, but another task.

**Comment by objeck** [comment]
It has been added.
