### ISSUE TITLE
[discussion] Brackets and Array/Collections

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#281]
You choose square brackets for Array (on Java and other C-like language I remember they use the curly braces). The Collections of Objeck is more of an abstract type that can't be manipulated directly like Array (can only modified by predefined methods). But if you have to choose which brackets to use with which Collections, what would you choose?

Related to #279 and #280, when you print the Array or Collections to the screen, you must do something to tell the users that this is an Array or Collections by formatting the output with the use of brackets. I will do some tests with Java and tell you which brackets they use.

Update: run in browser is so handy, here you are:

https://www.w3schools.com/java/java_arrays.asp

https://www.w3schools.com/java/java_arraylist.asp

(and many more in the same site)

Update: it seems the brackets they use on the syntax to initialize the Collections directly with the brackets they use to format the output to print the Collections to the screen could be different, such a mess!

**Comment by objeck** [comment]
So, I do not see an example in Java of an ``ArrayList`` being statically initialized, without the use of the ``Arrays.asList(..)`` method, which is similar to ``IntRef->FromArray(..)`` function in Objeck. 

Maybe I rename to ``IntRef->ToRef(..)``?

**Comment by iahung2** [comment]
> So, I do not see an example in Java of an `ArrayList` being statically initialized without the use of the `Arrays.asList(..)` method, which is similar to `IntRef->FromArray(..)` function in Objeck.
> 
> Maybe I rename to `IntRef->ToRefs(..)`?

Please choose a name that is descriptive so the users could at least guess what the method is doing without having to consult the API document. Btw, I don't see any usages for the method you added. I raised the issue from the beginning but after some research I think Objeck should remain the way it currently is. But I think it's rude to just close #276 as not planned so I reopened and waited inputs from you.

Perhaps the way is express my idea is confusing for you but the issue on this thread after various amendments from me is now how to pretty print Collections to the screen (which type of brackets and which format to use). For example, Java use square brackets to print Array, List, HashSet... to the screen and curly braces for HashMap.

**Comment by objeck** [comment]
Thanks for the feedback. I added ``ToString()`` to the generic collections. I believe the ``MultiMap`` is the last class left to update.

**Comment by objeck** [comment]
The features in this thread have been implemented.
