### ISSUE TITLE
[discussion] Initialize Collections using Arrays

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#284]
I think we need something more powerful than https://github.com/objeck/objeck-lang/issues/276#issuecomment-1666850999

The syntax could look like this:

```
vec := Vector->New()<Int>;
vec->AddAll([1,2,3]);
```

The syntax on https://github.com/objeck/objeck-lang/issues/276#issuecomment-1666850999 is counter intuitive and I think should be removed and replaced with the new syntax.

**Comment by objeck** [comment]
``Int`` and ``IntRef`` are not interchangeable array types.

**Comment by iahung2** [comment]
> `Int` and `IntRef` are not interchangeable array types.

OK. Then you could use the syntax like Java's `Collections.addAll()`.

**Comment by objeck** [comment]
Added the following methods to all of the "Ref" classes
* ``ToArray(..)`` to create a primitive array from a reference array
* ``FromArray(..)`` to create a reference array from a primitive array

For example
```
# static int array to intref array to intref vector
r := Collection.Vector->New(IntRef->FromArray([1, 2, 3]))<IntRef>;
r->Size()->PrintLine();

# intref vector to int array
p := IntRef->ToArray(r->ToArray());
p->PrintLine();
```

**Comment by iahung2** [comment]
> Added the following methods to all of the "Ref" classes
> 
> * `ToArray(..)` create a primitive array from a reference array
> * `FromArray(..)`  create a reference array from a primitive array
> 
> For example
> 
> ```
> # static int array to intref array to intref vector
> r := Collection.Vector->New(IntRef->FromArray([1, 2, 3]))<IntRef>;
> r->Size()->PrintLine();
> 
> # intref vector to int array
> p := IntRef->ToArray(r->ToArray());
> p->PrintLine();
> ```

@objeck Perhaps you misunderstood me. What I suggested is something much more powerful. It's basically about initializing Collections using Arrays. This offers a way to directly initialize Collections in a reasonable way that will not increase the complexity of the language.

Btw, the current API introduced by you is so obscure:

```
p := IntRef->ToArray(r->ToArray());
p->PrintLine();
```

`r` is a Vector so `r->ToArray()` is an array. Why do you convert `IntRef` to an array which take `r->ToArray()` which is already an array? I don't understand much about the Ref types of Objeck but this is so counter intuitive.

**Comment by objeck** [comment]
Primitives and references to primitives are two different types thus requiring conversions to switch between the datatypes. It is possible to write code that converts an array of primitives (i.e. [1,2,3]) into an array of type generic references however, that breaks the properties of generic programming by forcing tight coupling.

**Comment by objeck** [comment]
> > Added the following methods to all of the "Ref" classes
> > 
> > * `ToArray(..)` create a primitive array from a reference array
> > * `FromArray(..)`  create a reference array from a primitive array
> > 
> > For example
> > ```
> > # static int array to intref array to intref vector
> > r := Collection.Vector->New(IntRef->FromArray([1, 2, 3]))<IntRef>;
> > r->Size()->PrintLine();
> > 
> > # intref vector to int array
> > p := IntRef->ToArray(r->ToArray());
> > p->PrintLine();
> > ```
> 
> @objeck Perhaps you misunderstood me. What I suggested is something much more powerful. It's basically about initializing Collections using Arrays. This offers a way to directly initialize Collections in a reasonable way that will not increase the complexity of the language.
> 
> Btw, the current API introduced by you is so obscure:
> 
> ```
> p := IntRef->ToArray(r->ToArray());
> p->PrintLine();
> ```
> 
> `r` is a Vector so `r->ToArray()` is an array. Why do you convert `IntRef` to an array which take `r->ToArray()` which is already an array? I don't understand much about the Ref types of Objeck but this is so counter intuitive.

Primitives and references to primitives are two different datatypes, thus requiring conversions between the types. It is possible to write code that converts an array of primitives (i.e., Int ``[1,2,3]``) into an array of qualified generic references (i.e., ``IntRef[]``); however, that breaks the properties of generic programming by enforcing tight coupling. 

The Java [``Arrays``](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html) class is primarily used to manipulate arrays and create Collections (i.e., ``List``) from arrays via methods like ``asList()`` it is not for converting say a Java ``int`` array to a Java ``Integer`` array. 

The following Java code does the latter:
``Integer[] array = new Integer[]{1, 2, 3, 4};``

This Objeck code is equivalent:
``array := IntRef->FromArray([1,2,3,4])``

One can also write 3 to 5 lines of code to avoid using the function above.

**Comment by iahung2** [comment]
@objeck What I want to tell you this piece of code is obscure:

```
p := IntRef->ToArray(r->ToArray());
p->PrintLine();
```

`r` is a Vector so `r->ToArray()` is an array. Why do you convert `IntRef` to an array which take `r->ToArray()` which is already an array?

**Comment by iahung2** [comment]
> Primitives and references to primitives are two different datatypes, thus requiring conversions between the types. It is possible to write code that converts an array of primitives (i.e., Int `[1,2,3]`) into an array of qualified generic references (i.e., `IntRef[]`); however, that breaks the properties of generic programming by enforcing tight coupling.
> 
> The Java [`Arrays`](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html) class is primarily used to manipulate arrays and create Collections (i.e., `List`) from arrays via methods like `asList()` it is not for converting say a Java `int` array to a Java `Integer` array.
> 
> The following Java code does the latter: `Integer[] array = new Integer[]{1, 2, 3, 4};`
> 
> This Objeck code is equivalent: `array := IntRef->FromArray([1,2,3,4])`
> 
> Note the conversation work is done by the `Integer` class in Java and the `IntRef` class in Objeck. Conversely, one can write 3 to 5 lines of code to avoid using the above function.

The Java `Integer` class has no such obscure `ToArray` method:

https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html

**Comment by objeck** [comment]
The ``Integer`` array constructor does the conversion.

**Comment by iahung2** [comment]
> The `Integer` array constructor does the conversion.

If you have decided this is the optimal syntax, then I don't want to argue with you any further. One more quirk of the language is noted.

**Comment by iahung2** [comment]
> I make no claims that the syntax is "optimal," as that is a matter of opinion. I have implemented most of your feedback while looking past disparaging remarks. Initilizating a generic `Vector` can be done in many ways and is not a language limitation.

English is not my native language, so the use of words by me is not `optimal`, either. I'm very sorry about that if it caused confusion or misunderstanding.

> I am seeking maintainers so that I may work on other aspects of the language. The goal is to empower maintainers to make independent decisions and contribute new ideas.

I hope I could help but I can't. I don't have CS background.

**Comment by objeck** [comment]
@iahung2 Thank you for the feedback
