### ISSUE TITLE
Compilation speed concerns

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#295]
### Discussed in https://github.com/objeck/objeck-lang/discussions/294

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** August 10, 2023</sup>
Objeck has expanded greatly compared to when I knew it. The compilation speed is also worsening. This is normal for any large C++ project. The problem is that the build system of Objeck is not fully paralleled. If you pay a bit more attention to what is printed on the screen, you will see that `make` tells you:

`make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`

The way you designed your makefiles makes it impossible to fully utilize the parallelization feature of `make`, and a lot of code has to be built again and again. I think it's time to change it. Either redesign your makefiles or switch to `cmake` or `meson`. This will also help reduce the compilation time on Github Actions.</div>

**Comment by objeck** [comment]
Makd updates to makefiles. Note that linking is still time-consuming.

**Comment by iahung2** [comment]
> Make updates to makefiles. Note that linking is still time-consuming.

On UCRT64 you could install the package `mingw-w64-ucrt-x86_64-lld` and pass `-fuse-ld=lld` to g++ and see if the linking speed is improved. I'm currently unable to build Objeck from source to check it myself.
