### ISSUE TITLE
Add sample code for embedding Objeck in C++

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#299]
### Discussed in https://github.com/objeck/objeck-lang/discussions/298

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** August 11, 2023</sup>
The sample should be able to handle code snippets and a whole source file. I'm very sorry for needing you to spoon-feed me. I'm very bad at coding. Thank you.</div>

Should be part of `Getting Started`.

**Comment by objeck** [comment]
I will look into this further. 

For now, refer to [this](https://github.com/objeck/objeck-lang/blob/master/core/module/lang.cpp). The code is not too complex; however, the build and linking process can be.

**Comment by iahung2** [comment]
> I will look into this further.
> 
> For now, refer to [this](https://github.com/objeck/objeck-lang/blob/master/core/module/lang.cpp). The code is not too complex; however, the build and linking process can be.

It's not for no reason that I asked for sample code. I don't want to be rude, but the API is as obscure as possible. The header `lang.h` has no comment, and even after I read `lang.cpp` very carefully, I still have no idea how to use it. Why are there both `source` on the constructor `ObjeckLang` and `file` on the method `Compile`? Which is the usage for each of them? There is absolutely no comment, no documentation, nothing.

**Comment by objeck** [comment]
I will create a documented example after I complete the SQLite work.

**Comment by iahung2** [comment]
I'm still looking forward to see the sample code.

**Comment by objeck** [comment]
Here's an [example](https://github.com/objeck/objeck-lang/blob/master/core/module/example/example.cpp).
