### ISSUE TITLE
[OBB] says it cant find the current working directory

### ISSUE THREAD

**Issue by beo-dev** [objeck/objeck-lang#300]
so it says:
 ```
>>> Unable to determine the current working directory <<<
```
and im not sure how to circumvent this

**Comment by iahung2** [comment]
Your CWD has Unicode characters?

**Comment by objeck** [comment]
> so it says:
> 
> ```
> >>> Unable to determine the current working directory <<<
> ```
> 
> and im not sure how to circumvent this

Thanks, can you provide a sample directory name that fails on your system? I will try to recreate and fix the issue. 

Did you download or build Objeck?

**Comment by objeck** [comment]
@beo-dev 

I successfully tested the example below with ``origin/master``. The source files for the ``obb`` utility have not been changed in 2-5 months. Please provide an example, like the one below, so I can recreate the issue.

Compile and test code:
```
> obc hello_0.obs
Compiled 1 class.
Linked 15 library classes.
Wrote target file: 'hello_0.obe'.
```

```
> obr hello_0.obe
Hello World
Καλημέρα κόσμε
こんにちは 世界
```

Create and test native executable:
```
> obb -src_file hello_0.obe -to_dir hello -to_name hello
Created portable runtime for: 'hello_0.obe' in directory 'hello\hello'
```

```
> hello.exe
Hello World
Καλημέρα κόσμε
こんにちは 世界
```

**Comment by iahung2** [comment]
Maybe this has never really resolved and the OP is building from source on MSYS2 like I used to do:

https://github.com/objeck/objeck-lang/discussions/221

**Comment by objeck** [comment]
> Maybe this has never really been resolved, and the OP is building from source on MSYS2 like I used to do:
> 
> #221

Thanks, these are two separate issues. For #221, the issue was resolved, and the directory structure was updated.

**Comment by iahung2** [comment]
@beo-dev Do you still care about this? If not, I suggest to close this issue.

**Comment by iahung2** [comment]
I'm unsubscribed from this thread.
