### ISSUE TITLE
Why there are two lines of `make clean; make -j3`?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#307]
https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_posix.sh#L42

https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_posix.sh#L45

https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_msys2-ucrt.sh#L27

https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_msys2-ucrt.sh#L30

https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_msys2-clang.sh#L27

https://github.com/objeck/objeck-lang/blob/4d130de578707fa2a3181bef5f8e7c4151460bf3/core/release/deploy_msys2-clang.sh#L30

**Comment by objeck** [comment]
The one line, with two statements, is to invoke a clean rebuild.

**Comment by objeck** [comment]
Ok, let look at that
