### ISSUE TITLE
`module/example` is printing nonsense on MSYS2 CLANG64

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#312]
@objeck Try and test it yourself.

**Comment by iahung2** [comment]
Could be related to https://github.com/msys2/MINGW-packages/discussions/18233

**Comment by iahung2** [comment]
Could you reproduce it? It maybe because of https://github.com/msys2/MINGW-packages/discussions/18233 and https://github.com/msys2/MINGW-packages/discussions/18233 is caused by my failing SSD. I replaced the disk and now can no longer reproduce the problem.

**Comment by iahung2** [comment]
My SSD is gone. I have replaced it with a new one. I was confused in the process and made some wrong conclusions. The problem on this thread is very real. This is what it printed on the screen:

```
$ ./example hello.obs
捥潨›਱捥潨›ਲ
```

**Comment by objeck** [comment]
I have not looked at clang yet.

**Comment by iahung2** [comment]
It seems the problem is gone 😄
