### ISSUE TITLE
[Module code] The Execute method of ObjeckLang requires `cmd_args`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#315]
Please add an overloaded version of `Execute` that doesn't require `cmd_args` for convenient. Thank you.

p/s: I tried to run `hello_0.obs` which is a program that doesn't need `cmd_args` and I'm sure there are many programs like that. I tried to use `lang.Execute(L"");`. It compiled fine but segmentation fault when run.

**Comment by objeck** [comment]
Done
