### ISSUE TITLE
How to handle va_list on binding code?

### ISSUE THREAD

**Issue by objeck** [objeck/objeck-lang#327]
### Discussed in https://github.com/objeck/objeck-lang/discussions/326

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September  1, 2023</sup>
For example:

`int test1(int x, int y, ...)`

`int test2(int x, int y, va_list args)`</div>

**Comment by objeck** [comment]
See #336

**Comment by iahung2** [comment]
Frankly speaking, this is not a duplicate of #336. This is a question about how to handle `va_list` in binding code. #336 is a question about whether the language supports Varargs at all.

**Comment by objeck** [comment]
Consider mapping the C++ ``va_list`` object to an Objeck array type.

**Comment by iahung2** [comment]
> Consider mapping the C++ `va_list` [object ](https://en.cppreference.com/w/c/variadic/va_list) to an Objeck array or list type.

Example code, please? Btw, when I raised this question I pretty much think I will follow the .NET's P/Invoke way, that is define the function with a fixed number of arguments.
