### ISSUE TITLE
`sys.h` - `CharacterToBytes` doesn't do any conversions

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#329]
Unlike `BytesToCharacter` which does both the check and the conversion, `CharacterToBytes` only does the check but no conversions.

https://github.com/objeck/objeck-lang/blob/ecd3af4f24f0b74b816e864e6ee9d563d7f23dbe/core/shared/sys.h#L251-L265

Btw, should `buffer` be `std::wstring` rather than an array of `wchar_t`? I think `UnicodeToBytes` needs `std::wstring` as input.

Please have a look at it. Thank you.

**Comment by objeck** [comment]
For this function, the results are stored in the ``out`` variable. The return value is success or failure.

**Comment by iahung2** [comment]
> For this function, the results are stored in the `out` variable. The return value is success or failure.

Yes, I know. This is the same class as `BytesToCharacter`. But please have a look at it, unlike the implementation of `BytesToCharacter`, this `CharacterToBytes` doesn't do the conversion. The `out` variable is pretty much unused. Yes, it's only used once on the if statement but this is not real conversion.
