### ISSUE TITLE
`sys.h` - Please add methods to convert `char` to `wchar_t` and `wchar_t` to `char`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#330]
You only have `BytesToCharacter` and `CharacterToBytes`. I think `CharToWChar` and `WCharToChar` will be useful.

**Comment by objeck** [comment]
That is what the existing functions do. 

They convert a ``wchar_t`` string to a ``char`` string and vice versa. Note that the ``wchar_t`` type is either 16- or 32-bytes, depending upon the host. 

A``char`` byte stream is UTF-8, and UTF-8 is used for interface I/O as it is ASCII backward compatible.

**Comment by iahung2** [comment]
> That is what the existing functions do.
> 
> They convert a `wchar_t` string to a `char` string and vice versa. Note that the `wchar_t` type is either 16- or 32-bytes, depending upon the host.
> 
> A`char` byte stream is UTF-8, and UTF-8 is used for interface I/O as it is ASCII backward compatible.

No, I'm not mentioning about strings. I mean a single character. Currently there is no methods to convert a single `char` to `wchar_t` or `wchar_t` to `char`. You could see I didn't add the `*` symbol because I mean a single character not array of characters (aka strings).

**Comment by objeck** [comment]
I have not looked much into single-character conversion as I do not do them often.

**Comment by objeck** [comment]
A 1:1 character conversion from Unicode ``wchar_t`` to a ``char`` normally ASCII is impossible for a character whose numeric value is greater than 0xff.

 ``BytesToCharacter`` takes a string of bytes and converts them into a Unicode character. ``CharacterToBytes`` takes a Unicode character and converts it into a string of bytes. 

The underlying ``WideCharToMultiByte`` function in Windows and ``wcstombs`` function on POSIX hosts are used for single-character conversions (see this [write-up](https://stackoverflow.com/questions/3019977/convert-wchar-t-to-char)). 

Not sure what else I can do on my end as I am unsure what to "fix".

**Comment by iahung2** [comment]
`wchar_t` is UTF-16 and `char` is UTF-8. Both of them are multibytes. The terms MultiBytes (aka Bytes) and Unicode being used by you is indeed a deception from Microsoft. UTF-8 is also Unicode.

**Comment by iahung2** [comment]
OK. Let's jump out of this can of worms and work on something more interesting instead 😄

**Comment by objeck** [comment]
Correct, we should consider ``UTF-8`` to ``xyz``, which may not be a 1:1 character conversion. How can a single byte ``wchar_t`` be converted to a **single** ``char`` value?
