### ISSUE TITLE
`sys.h` - Add overloaded methods for `BytesToCharacter` and `CharacterToBytes`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#331]
The same way you did with `BytesToUnicode` and `UnicodeToBytes`. There should be both the methods that return a boolean and the methods that do the conversion directly.

**Comment by objeck** [comment]
There are, the functions are overloaded, for [example](https://github.com/objeck/objeck-lang/blob/master/core/shared/sys.h#L95).

**Comment by iahung2** [comment]
> There are, the functions are overloaded, for [example](https://github.com/objeck/objeck-lang/blob/master/core/shared/sys.h#L95).

I'm talking about `BytesToCharacter` and `CharacterToBytes`. I suggest they have overloaded versions like `BytesToUnicode` and `UnicodeToBytes`.
