### ISSUE TITLE
How to handle the void pointer on binding code?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#332]
### Discussed in https://github.com/objeck/objeck-lang/discussions/325

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September  1, 2023</sup>
For example, the origin C code is a struct with `void*` members or a function that takes `void*` parameters or a function that returns `void*`. How could I map them them to Objeck code?</div>

**Comment by objeck** [comment]
[Here's](https://github.com/objeck/objeck-lang/blob/master/core/compiler/lib_src/sdl2.obs#L948) an example. 

A C/C++ structure can be mapped to an Objeck ``Int``. The Objeck ``Int`` can point to any 64-bit value.
