### ISSUE TITLE
Does Objeck support Varargs?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#336]
### Discussed in https://github.com/objeck/objeck-lang/discussions/335

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September  5, 2023</sup>
Please correct me if I'm wrong. But it seems Objeck doesn't support Varargs.</div>

**Comment by iahung2** [comment]
@objeck

**Comment by objeck** [comment]
Objeck does not support variable-length arguments. 

The assumption is arrays, vectors, lists, and maps can be used to pass such arguments to a function. The first I ran into variable arguments was while reading legacy C code. 

Given modern data structures, including arrays, the need for named variable arguments seems dated.

Thoughts?

**Comment by iahung2** [comment]
Both Java and C# support Varargs, albeit with different syntax. Python and PHP also support Varargs. This is on the language level, though. I'm not talking about the FFI. For example, .NET's P/Invoke doesn't support Varargs so the external functions will always need to be defined with a fixed number of arguments.

**Comment by iahung2** [comment]
Btw, this is only a question. I'm not asking you to add support for Varargs. Please make it clear.

**Comment by objeck** [comment]
Thanks for the information. 

I am inclined only to add it if it is a required feature, meaning there is no reasonable "workaround." Adding a ``var_args`` like object to unpack a variable length named parameter can be accomplished using existing types (i.e., array, vector, array, map). 

The time required to add, test, and **support** a complex feature that may be rarely used seems high.

**Comment by iahung2** [comment]
I guessed Objeck doesn't support Varargs from the beginning. But I want to know for sure so I asked you. If the language itself doesn't support Varargs then the logical way is to follow .NET's P/Invoke, that is define the external function with a fixed number of arguments. This is my idea. You might come up with something more complex like mapping the C++'s `va_list` object to Objeck's array or list type like what you said on https://github.com/objeck/objeck-lang/issues/327#issuecomment-1707580206.

**Comment by objeck** [comment]
> Btw, this is only a question. I'm not asking you to add support for Varargs. Please make it clear.

Understand, I do not see a clear need for it. The ability to support "va_args" variables was considered when Objeck was designed. The feature proved too messy to implement as there were existing workarounds.
