### ISSUE TITLE
An alternative foreign function interface based on `libffi`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#351]
### Discussed in https://github.com/objeck/objeck-lang/discussions/350

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September 13, 2023</sup>
LibFFI is very commonly used: https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-libffi

Java's JNA is based on LibFFI. The newly launched JNR is also based on LibFFI. Python also uses LibFFI...

The current JNI style FFI of Objeck is not hard and indeed very simple and elegant compared to Java's JNI but is time consuming to use. I suggest adding an alternative FFI for Objeck based on LibFFI. It makes a clear distinction. For performance critical jobs use the JNI style FFI. For quickly mockup something that is usable use the alternative LibFFI based FFI. The alternative LibFFI based FFI will be written using the well established JNI style FFI. e.g: `libobjk_ffi.dll`/`libobjk_ffi.so` and `ffi.obl`. Do you think my idea is feasible? If yes, please consider. Thank you.</div>

**Comment by objeck** [comment]
I will revisit this after implementing the next round of enchantments.
