### ISSUE TITLE
Call Objeck methods from C++

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#355]
### Discussed in https://github.com/objeck/objeck-lang/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** February  8, 2023</sup>
Is it possible? It's possible to call Java from C++ using JNI:

https://www.baeldung.com/jni#2-using-objects-and-calling-java-methods-from-native-code</div>

Note: This is about calling methods written in Objeck from C++.

**Comment by iahung2** [comment]
> Not possible, the VM runs programs not functions with programs.

Why it's possible with other languages that also run on a VM? Objeck's architecture is anything different?

Take for example: Mozilla Rhino and Java Nashorn, V8 (otherwise there would be no NodeJS and Deno), Python,... Just create a new interpreter object and you could evaluate anything you want. What make Objeck so different?

**Comment by objeck** [comment]
Again, Objeck executes programs, not functions. It may be possible to execute a function if there is an entry point, i.e., like ``Main``. Please, understand I do not have time to explore all of your suggestions.

**Comment by objeck** [comment]
It seems interesting, however, porting seems timely.
