### ISSUE TITLE
Evaluate Objeck code in C++

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#357]
Note: Currently, only a whole source file is supported. This is about evaluating a snippet of code.

**Comment by objeck** [comment]
Not possible

**Comment by iahung2** [comment]
> Not possible

Why it's possible with other languages that also run on a VM? Objeck's architecture is anything different?

Take for example: Mozilla Rhino and Java Nashorn, V8 (otherwise there would be no NodeJS and Deno), Python,... Just create a new interpreter object and you could evaluate anything you want. What make Objeck so different?
