### ISSUE TITLE
Should Objeck support positive zero/negative zero like Java?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#361]
### Discussed in https://github.com/objeck/objeck-lang/discussions/188

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** March 28, 2023</sup>
https://www.vinaysingh.info/negative-zero/</div>

**Comment by objeck** [comment]
Is there a need?

**Comment by iahung2** [comment]
> Is there a need?

Math. Both C# and Java have.
