### ISSUE TITLE
Should Objeck support NaN?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#362]
### Discussed in https://github.com/objeck/objeck-lang/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** March 27, 2023</sup>
https://www.baeldung.com/java-not-a-number</div>

**Comment by objeck** [comment]
Is there a need?

**Comment by iahung2** [comment]
> Is there a need?

Math. Both C# and Java have.

**Comment by objeck** [comment]
I will add NaN and +/- infinity support to the next release. I believe I found the C++ ``std`` equivalents.

**Comment by objeck** [comment]
Added: ``Int->NaN()``, ``Int->Inf()``, ``Int->NegInf()``,  ``Float->NaN()``, ``Float->Inf()`` and ``Float->NegInf()``.
