### ISSUE TITLE
IEEE Standard 754 Floating Point Numbers

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#363]
It seems Objeck's implementation of floating point numbers does not conform to this standard.

Please have a look: #360 #361 #362

**Comment by objeck** [comment]
Objeck uses the IEEE-754 format for 64-bit decimal values.

**Comment by iahung2** [comment]
> Objeck uses the IEEE-754 format for 64-bit decimal values.

You do not fully implement the standard. It can't be, without https://github.com/objeck/objeck-lang/issues/360 https://github.com/objeck/objeck-lang/issues/361 https://github.com/objeck/objeck-lang/issues/362.
