### ISSUE TITLE
Objeck and WebAssembly

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#364]
On #85, you said you were interested in WebAssembly. Since that thread was closed, I created this issue to continue the discussion about Objeck and WebAssembly. Are you still interested in WebAssembly?

**Comment by objeck** [comment]
This is a big lift and project in itself.

**Comment by iahung2** [comment]
> This is a big lift and project in itself.

It's only a question. It's not a feature request. I personally don't care about WASM.

**Comment by objeck** [comment]
Understand, more plans at this time.
