### ISSUE TITLE
Setting up Nightly release?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#370]
### Discussed in https://github.com/objeck/objeck-lang/discussions/354

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September 24, 2023</sup>
Like this: https://github.com/AdeptLanguage/Adept/releases/tag/Nightly

So you don't have to make new releases as regularly as you do now.</div>

**Comment by objeck** [comment]
Nightly builds are not supported out-of-the-box by GitHub Actions. There appears to be a workaround I'm exploring.
