### ISSUE TITLE
Leveraging the Objeck VM to run other languages?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#372]
### Discussed in https://github.com/objeck/objeck-lang/discussions/366

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September 24, 2023</sup>
Is it possible? Or is the Objeck VM so tied to the Objeck language? Running other languages on a VM that was originally designed for one language is not rare. The JVM comes to mind immediately. It was originally designed for Java, but now there are a bunch of JVM languages available. They are even going further with GraalVM. The Elixir language is also designed to run on the Erlang VM from the beginning.</div>

**Comment by objeck** [comment]
Yes, however, one would need to port the language. Objeck is a general-purpose VM with a supporting instruction set.
