### ISSUE TITLE
JsonParser very poor performance

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#383]
Compared to equivalent C code that returned the result almost instantly, the Objeck version took several seconds to return the result.

**Comment by objeck** [comment]
Please forwrd the code you tested

**Comment by iahung2** [comment]
```
use Collection;
use Data.JSON;
use System.IO.Filesystem;

class Test1 {
	function : Main(args : String[]) ~ Nil {
		data := FileReaderWriter->ReadFile("test.json")
		parser := Data.JSON.JsonParser->New(data)
		if(parser->Parse()) {
			root := parser->GetRoot()
			foobar := root->FindElements("test/foo/bar/[0]/foobar")->GetString()
			foobar->PrintLine()
		}
	}
}
```

The C code is using JSON-GLib.

**Comment by iahung2** [comment]
I don't want to share either the JSON file or the C code.

**Comment by objeck** [comment]
> I don't want to share either the JSON file or the C code.

Please share both.

**Comment by iahung2** [comment]
> Please share both.

JSON contains personal data. The code posted above was already modified to remove personal data. The C code is quickly assembled to see if parsing JSON is that slow in general. It turned out that only the JsonParser of Objeck is slow. That's it.

p/s: I deleted the C code. JSON is about 2MB and contains bookmarks. I decided to use C# and Json.NET to parse this JSON, so you could keep this issue as closed. I don't want to go any further, but please note that I have informed you about this problem.
