### ISSUE TITLE
Serialize/Deserialize XML

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#385]
Please add support for this. Thank you.

**Comment by JohnyKapo** [comment]
Hello interesting issue. Is it possible to get assigned and work on it?

**Comment by objeck** [comment]
Support already exist

**Comment by iahung2** [comment]
> Support already exist

Can't find anything like that on the API document. An example, please? Check Newtonsoft's Json.NET to see what the feature I'm suggesting looks like before comment, please.

**Comment by objeck** [comment]
> > Support already exist
> 
> Can't find anything like that on the API document. An example, please? Check Newtonsoft's Json.NET to see what the feature I'm suggesting looks like before comment, please.

Take a look at the ``XmlElement`` class. Note that XML and JSON have supporting parsing frameworks per their specifications.

**Comment by iahung2** [comment]
> > > Support already exist
> > 
> > 
> > Can't find anything like that on the API document. An example, please? Check Newtonsoft's Json.NET to see what the feature I'm suggesting looks like before comment, please.
> 
> Take a look at the `XmlElement` class. Note that XML and JSON have supporting parsing frameworks per their specifications.

Still don't see anything like the feature I'm suggesting. Again, please check Newtonsoft's Json.NET to see what the feature I'm suggesting looks like before comment. Thanks.

p/s: you can see the description right on the website of it: https://www.newtonsoft.com/json
