### ISSUE TITLE
`obc` and `obi`: add a switch to force all methods to be `native`

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#387]

**Comment by objeck** [comment]
Is this for source or source and libraries? I feel libraries need their existing flags (i.e. ``native``) for consistent performance.

**Comment by objeck** [comment]
I will look into this for the next release. This is more of a runtime vs. compiler issue. The compiler may link libraries that use the ``native`` keyword. If so, the JIT compiler must be disabled within the VM. I am also concerned with overall performance.

**Comment by tqo50396** [comment]
> I will look into this for the next release. This is more of a runtime vs. compiler issue. The compiler may link libraries that use the `native` keyword. If so, the JIT compiler must be disabled within the VM. I am also concerned with overall performance.

Don't think too much. It's source-level and only affects the source files being compiled. There is nothing to do with the runtime. When I proposed this, I didn't think you would think that far. My opinion is that everything should be JIT-ed. The keyword `native` sounds redundant to me.

**Comment by objeck** [comment]
No impact on the source programmer's source code. The idea is to empower the programmer to let them decide to want they want JIT compiled in their code. On the otherhand, JIT compiling everything is efficient.

**Comment by tqo50396** [comment]
> No impact on the source programmer's source code. The idea is to empower the programmer to let them decide to want they want JIT compiled in their code. On the otherhand, JIT compiling everything is efficient.

I don't get this idea. We disagreed with each other again. Btw, this suggestion is about a compiler switch, not about forcing JIT by default with no options to customize. It's just a shortcut to make the programmer's life easier so he doesn't have to write `native` everywhere. His ability to customize everything is not affected, just don't use the compiler switch.

**Comment by objeck** [comment]
So, the programmer should not use the ``native`` keyword. What am I missing? Are you asking for a compiler switch to disable the programmer's use of the keyword ``native``?

**Comment by tqo50396** [comment]
> So, the programmer should not use the `native` keyword. What am I missing? Are you asking for a compiler switch to disable the programmer's use of the keyword `native`?

 Regardless of the source code use `native` or not, a compiler switch will force `native` so everything be JIT-ed (this issue, #387). My main usage for this is that I don't have to write `native` everywhere. Issue #388 is the reverse of this, as it will force everything to be not JIT-ed.

**Comment by objeck** [comment]
Thanks, I will look into it. However, performance may suffer. Not all code needs to be JIT compiled. The compiler optimizes all code, rather JIT compiler or not at runtime.

**Comment by tqo50396** [comment]
> Thanks, I will look into it. However, performance may suffer. Not all code needs to be JIT compiled. The compiler optimizes all code, rather JIT compiler or not. At runtime, the JIT compiler flag is honored.

Now I struggled to understand what you are talking about.

**Comment by objeck** [comment]
JIT comping all methods/functions has a runtime hit which is not justified in most cases. It is justified if the methods/functions are computationally intensive and are called multiple times within the code.

Simple calls like getters/setters are optimized to avoid function/method calls, and more aggressive inlining is done after that.

Please send me a code sample so that I can test and benchmark your request. Implementing your request is easy, but I worry about side effects.  

Refer: https://en.wikipedia.org/wiki/Just-in-time_compilation

**Comment by tqo50396** [comment]
Please close this issue and remove it from the roadmap. I don't need this feature anymore. Thank you.

**Comment by objeck** [comment]
Okay, thank you for the feedback.

For reference, this is the optimization pipeline.

Optimizations in list order:
1. Jump optimizations
1. Constant folding
1. Getter/Setting inlining
1. Dead store removal
1. Constant propagation
1. Method inlining
1. Strength reduction
1. Instruction optimization

At runtime, bytecode may be translated to machine code at the programmer's request.

**Comment by tqo50396** [comment]
> Additionally, at runtime, bytecode may be translated to machine code at the programmer's request.

Isn't it AOT?

**Comment by objeck** [comment]
> > Additionally, at runtime, bytecode may be translated to machine code at the programmer's request.
> 
> Isn't this AOT?

No, that is compiling bytecode into machine code before runtime.
