### ISSUE TITLE
Ordered or Unordered?

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#395]
> Again, my time is limited, and I tend only to implement new library classes if required. Adding **more** to Objeck means more testing and maintenance.

_Originally posted by @objeck in https://github.com/objeck/objeck-lang/discussions/375#discussioncomment-7128411_

Yeah I know. I don't ask you to implement anything. This is only a question.

It seems all containers in Collections are Sorted, isn't it? There is no Unsorted versions, isn't it?

That's what I want to know. Thanks.

**Comment by objeck** [comment]
List, Arrays and Queue are unsorted
