### ISSUE TITLE
What is the closest thing to `std::map`?

### ISSUE THREAD

**Issue by iahunq2** [objeck/objeck-lang#396]
Please pardon my ignorant. I know I'm stupid. I don't know anything about Computer Science. I'm currently using `Map`. But I found there is `Hash`, too. I didn't see `Hash` the last time I read the API Document. I know I'm careless but it's not something to talk in this thread. I only want to know what is the closest thing to `std::map`. Thank you.

**Comment by objeck** [comment]
The ``Map`` class is most similar to a ``std::map`` class. It implements a  modified version of the red-black tree algorithm with a complexity of ``O(log n)`` and uses memory efficiently by allocating nodes as needed. 

The ``Hash`` class uses a hash function with a complexity of ``O(1)``, however, it allocates lots of unused memory. The classic trade is speed vs. memory. Both are sorted and faster look and insert times than ``Vectors`` or ``Lists``.
