### ISSUE TITLE
`obi`: add `-e` switch

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lang#400]
Shorthand for `-inline`.

**Comment by objeck** [comment]
Thanks, please update/modify this [spreadsheet](https://docs.google.com/spreadsheets/d/1e_F1RaxKoXGsi_6Xc0fdYVp35AuJ_Hc0_8pBDDCqonQ/edit?usp=sharing).

**Comment by objeck** [comment]
Thanks. Was I considering trying the short/long flag model? Thought? Mucking with flags will break stuff either way.
--file <filename> or -f  <filename>

**Comment by objeck** [comment]
added support for ``-inline`` and ``-i``

**Comment by objeck** [comment]
Thanks, added
