### ISSUE TITLE
Extremely poor performance of JsonParser

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#407]
In the old issue (#383), I failed to give you the sample code since the JSON file contains personal information (my bookmarks). Today, I did a cleanup of my system. I found the old sample code and I also found another complex and big enough JSON file to reproduce this issue (instead of my bookmarks). So, here you are.

Sample code:

```
use Data.JSON;

class Test {
    function : Main(args : String[]) ~ Nil {
        input := System.IO.Filesystem.FileReader->ReadFile("Web.MsHtml.json");
        if(input <> Nil) {
            parser := JsonParser->New(input);
            if(parser->Parse()) {
                root := parser->GetRoot();
                if(root <> Nil) {
                    constants := root->Get("Constants");
                    if(constants <> Nil) {
                        Constant1 := constants->Get(0);
                        if(Constant1 <> Nil) {
                            Constant1->Get("Name")->GetString()->PrintLine();
                        }
                    }
                }
            }
        }
    }
}

```

JSON file to test: https://raw.githubusercontent.com/marlersoft/win32json/main/api/Web.MsHtml.json

**Comment by objeck** [comment]
Thanks debugging and profiling.

Initial observations:
* Memory usage remains constant even when garbage collection is relaxed
* Most of the time is spent parsing the JSON with low CPU usage
* Considering parallelism, i.e., workers when parsing JSON arrays

**Comment by objeck** [comment]
The primary issue was memory management thresholds. The VM was tuned to run on low-memory hosts (i.e., RPI4). The initial memory size for programs, outside of RPI4, was changed from 4M to 1G. I am looking into setting the available to the 16th of the system memory.

For now, things should be faster.

**Comment by tqo50396** [comment]
> The primary issue was memory management thresholds. The VM was tuned to run on low-memory hosts (i.e., RPI4). The initial memory size for programs outside of RPI4 was changed from 4M to 1G. I am looking into setting available VM memory to the 16th of the system memory. For now, things should be faster.

https://www.baeldung.com/jvm-parameters

**Comment by objeck** [comment]
> > The primary issue was memory management thresholds. The VM was tuned to run on low-memory hosts (i.e., RPI4). The initial memory size for programs outside of RPI4 was changed from 4M to 1G. I am looking into setting available VM memory to the 16th of the system memory. For now, things should be faster.
> 
> https://www.baeldung.com/jvm-parameters

Yep, I believe the VM has an .ini config file as well. I have tried to avoid VM parameters but will now look into this further.

**Comment by tqo50396** [comment]
> I believe the VM has an .ini config file as well.

How that file look like? What about a sample `.ini config file`? This should be in `Getting Started`. No people will know and use this or that hidden feature except you.

**Comment by objeck** [comment]
> > I believe the VM has an .ini config file as well.
> 
> How that file look like? What about a sample `.ini config file`?

I will add it to the guide tomorrow. The file is ``config.prop`` however it only sets system properties.

**Comment by tqo50396** [comment]
> The file is `config.prop` however it only sets system properties.

It's in `lib\native\misc` directory. Seems to be useless to me.

**Comment by tqo50396** [comment]
> For now, things should be faster.

Was this issue really fixed or not? You have the JSON file, you could test.

**Comment by tqo50396** [comment]
> @tqo50396 I tested against the JSON file you provided. I then added auto-tuning parameters before adding support for manual configuration. All are based on the sample JSON file you gave me.

But what I want to know is simply if you fixed the issue or not. If you believed that you fixed it, you could close this issue. I can't test since I no longer use Objeck (nor do I want to fire up MSYS2 to compile Objeck from source).

**Comment by objeck** [comment]
Yes, it is fixed. I will close the issue.

**Comment by yyokyfo** [comment]
> Yes, it is fixed. I will close the issue.

The Objeck VM eats more RAM but the performance is still terrible. I'm very disappointed.

Download Adept here: https://github.com/AdeptLanguage/Adept/releases/tag/Nightly

Compile the code with `adept test.adept`:

```
pragma compiler_version '2.8'

import basics
import JSON

func main {
    json JSON = JSONFromFile("Web.MsHtml.json")

    if json.kind() == ::UNDEFINED {
        print("Failed to load json")
    } else {
        Constants <JSON> List = json.field("Constants").array().get()
        Constant0 JSON = Constants.get(0)
        print(Constant0.field("Name").string().get())
    }
}
```

You will see how fast it is compared to your parser.
