### ISSUE TITLE
What does Objeck look like in it earliest form?

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#409]
First, sorry for posting in `Issues`, as this thread should be posted in `Discussions`.

`OBC` has the `-alt` switch, which description is `-alt:    [optional] use alternative C like syntax`. This means, when Objeck was originally conceived, it doesn't have a C like syntax like it currently does.

**Comment by objeck** [comment]
Not exactly; the syntax for Objeck was derived from UML, which has ties to Pascal. 

The ``-alt`` flag was added because some users:

- Did not like the extra ``;`` at the end of some statement 
- Liked C comments better
- Did not like the not equal operator ``<>`` instead ``!-``

**Comment by objeck** [comment]
Yes, object model notation https://www.tutorialspoint.com/uml/uml_basic_notations.htm

**Comment by tqo50396** [comment]
> Yes, object modeling notation https://www.tutorialspoint.com/uml/uml_basic_notations.htm

UML is a diagram format, it's not even pseudocode. I don't see any Pascal like syntax out there. Can you give me an example UML program? In code? The code that you said is Pascal like? Don't give me the diagram!

**Comment by objeck** [comment]
> > Yes, object modeling notation https://www.tutorialspoint.com/uml/uml_basic_notations.htm
> 
> UML is a diagram format, it's not even pseudocode. I don't see any Pascal like syntax out there. Can you give me an example UML program? In code? The code that you said is Pascal-like? Don't give me the diagram!

I used UML to model objects and interfaces. the internals are a mixture of Java and Pascal-related syntax, all similar to C
