### ISSUE TITLE
Does the `-alt` switch still work?

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#410]
This is your answer in #273:

> It's obsolete but harmless.
> 
> It now allows you to use things such as C++ operators like `==`, `!=`, and comments.
> 
> The compiler used to require that a semi-colon is at the end of each statement block. This constraint was removed.

Could you clarify more? Especially, this line:

> The compiler used to require that a semi-colon is at the end of each statement block. This constraint was removed.

Yes, I know this constraint has been removed. But, is the `-alt` switch originally used to overcome this constraint, or does it force this constraint?

I'm exploring the `-alt` switch, because I'm really want to use C like comments.

**Comment by objeck** [comment]
Adding support for C comments so one does not have to use the ``-alt`` flag.

**Comment by objeck** [comment]
``-alt`` switchs operations like: objeck ``=`` to c ``==``, same for not equal. I will keep the switch, it is legacy and rarely asked about.
