### ISSUE TITLE
Document generator?

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#411]
The link in #102 is now invalid. Where is the tool located now?

**Comment by objeck** [comment]
Huh, I can see it. Below is the last comment on the thread.

---

[Here's](https://github.com/objeck/objeck-lang/tree/master/programs/doc) the code for documentation tool

**Comment by tqo50396** [comment]
> Huh, I can see it. Below is the last comment on the thread.
> 
> [Here's](https://github.com/objeck/objeck-lang/tree/master/programs/doc) the code for documentation tool

404 - page not found

**Comment by objeck** [comment]
I have no idea. The link is to the current repository.

**Comment by tqo50396** [comment]
> I have no idea. The link is to the current repository.

Check again. The directory `doc` doesn't exist. `objeck-lang/programs/doc` doesn't exist. I checked via the Github web interface. I even cloned the source tree. I can confirm it doesn't exist.

**Comment by tqo50396** [comment]
Yeah, I found it. It's renamed as `code_doc` and was put at `core/lib`. The script is now at `core/release`. You moved everything around all of the time. It's very hard to keep track of.
