### ISSUE TITLE
Update document generator to support C like comments

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#413]
Related to #411. I don't know where the tool is now or if it already supports C like comments. But I opened an issue nevertheless.

Do you know why I usually post the threads in batches? Because if I don't, I will forget them. Today, I'm working with Objeck. But tomorrow, I will work with other languages and will only come back to Objeck on the weekend. My workflow is a mess. I'm sorry if you think I'm spamming or if I'm causing you to feel inconvenient or annoyed. This is not my intention.

p/s: I decided to give Objeck another chance. I'm finding suitable uses for it, and I also no longer expect much from it like I used to.

**Comment by objeck** [comment]
Thanks for the feedback
