### ISSUE TITLE
Support using of Windows' ODBC

### ISSUE THREAD

**Issue by tqo50396** [objeck/objeck-lang#418]
When building for Windows, supports using Windows' ODBC instead of unixODBC. Windows has native support for ODBC.

**Comment by objeck** [comment]
This is the case today. The only target uses source is macOS.

**Comment by tqo50396** [comment]
> This is the case today. The only target uses source is macOS.

Is it the case on MSYS2? I found unixODBC on the list of packages needed to install: `mingw-w64-ucrt-x86_64-unixodbc`.

**Comment by objeck** [comment]
In those instances, ODBC support is provided via libraries. The source code is not precompiled, the same goes for Windows.
