### ISSUE TITLE
UCRT64 -Wcpp

### ISSUE THREAD

**Issue by yyokyfo** [objeck/objeck-lang#427]
```
C:/msys64/mingw64/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
   15 | #warning Please include winsock2.h before windows.h
      |  ^~~~~~~

```

**Comment by yyokyfo** [comment]
This message seems to come from the openssl headers. If it's the case, we can't do anything with it.

**Comment by objeck** [comment]
I agree, I have tried to "fix it" however, the OpenSSL headers bring in ``window.h`` include.
