### ISSUE TITLE
MINGW64 Environment

### ISSUE THREAD

**Issue by yyokyfo** [objeck/objeck-lang#429]
`error: 'SetProcessInformation' was not declared in this scope; did you mean 'SetTokenInformation'?`

p/s: works on UCRT64, fails on MINGW64 (MSVCRT).

**Comment by yyokyfo** [comment]
I didn't know that Objeck requires UCRT. Sorry.

**Comment by objeck** [comment]
I will disable low energy more for MSVCRT

**Comment by yyokyfo** [comment]
> I will disable low energy more for MSVCRT

How could you tell if it's MSVCRT or UCRT?

**Comment by objeck** [comment]
Add a preprocess flag for ``MSVCRT``. I suspect one already exists.

**Comment by yyokyfo** [comment]
> Add a preprocess flag for `MSVCRT`. I suspect one already exists.

Let's do something more useful, like fixing your JsonParser.
