### ISSUE TITLE
Dump GTK

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#433]
You don't want to work on it. I can't work on it because it's out of my ability. It's better to dump it.

Note: GTK needs you to install Xorg (XQuartz) to work on macOS. It doesn't support Cocoa.

**Comment by objeck** [comment]
Work is not planned

**Comment by iahung2** [comment]
> Work is not planned

`Dump GTK` means remove it. Is my English that bad?

**Comment by objeck** [comment]
It is not being built; it is under "experimental", the code generators are reuseable. Why take it out?

**Comment by iahung2** [comment]
> It is not being built; it is under "experimental", the code generators are reuseable. Why take it out?

OK.
