### ISSUE TITLE
IUP binding

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#434]
If need a GUI library, choose IUP. It is the easiest to wrap. The API is very clean. There is C++ OOP wrapper in `iup_plus.h`.

https://sourceforge.net/projects/iup/files/3.31/Windows%20Libraries/Dynamic/iup-3.31_Win64_dll17_lib.zip/download

Note: Ignore the `iuplua*.h`, we have nothing to do with them.

**Comment by objeck** [comment]
Thanks. I am now focusing on ML. 

The GUI work is dated, and many people preferred interface with their web browser.

**Comment by iahung2** [comment]
> Thanks. I am now focusing on ML.
> 
> The GUI work is dated, and many people preferred interface with their web browser.

OK.
