### ISSUE TITLE
Add the Delphi range data type

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#435]
Range-based a type is a subset of values of an integer, character , or enumerated type and is described as a..b, where a - lower, b - upper limit of the interval type, a< b:

```
var
  intI: 0..10;
  intC: 'a'..'z';
  intE: Mon..Thr; 
```

The type that a range type is based on is called the base basic type for that range type. Values of the range type occupy the same amount of memory as values of the corresponding base type.

Note: this is the description of Delphi range data type. What I'm proposing is something like `Collection.Range`.

https://realpython.com/python-range/

**Comment by iahung2** [comment]
Delphi range data type in Objeck would be implemented as ordered or unordered?

**Comment by iahung2** [comment]
According to Math, it should be ordered.

**Comment by iahung2** [comment]
Frankly speaking, I don't know if it's ordered or unordered even in Delphi!

**Comment by objeck** [comment]
Merge with #447
