### ISSUE TITLE
Add Tuples data type

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#436]
.NET's `System.Tuple`.

**Comment by objeck** [comment]
Objeck is statically typed with type erase like Java refer to https://codegym.cc/groups/posts/java-tuple. What does that mean, retiving values from a tuple requires casting.

**Comment by iahung2** [comment]
> Objeck is statically typed with type erase like Java refer to https://codegym.cc/groups/posts/java-tuple. What does that mean, retiving values from a tuple requires casting.

Isn't C# also statically typed? Btw, please just ignore this.

**Comment by objeck** [comment]
Yes, however c# it does not support type erasure. special instructions were created to support, the dynamic generation of such properties. for example, accessing ‘item1’ in code without it being defined.

**Comment by objeck** [comment]
similar in kotlin

**Comment by iahung2** [comment]
> Yes, however c# it does not support type erasure. special instructions were created to support, the dynamic generation of such properties. for example, accessing ‘item1’ in code without it being defined.

OK. I got it.

**Comment by iahung2** [comment]
Oops, C++ has `std::tuple`!

https://www.geeksforgeeks.org/tuples-in-c/

Perhaps C++ style Tuple is more suitable to Objeck. I should do a Google search to see if C++ has it or not. I always use C# as the reference, second Java. I rarely use C++ as the reference. I love C# the most. I'm biased towards .NET, I have to admit.

**Comment by objeck** [comment]
Noticed the remapping of values done by the compiler.

    // Use of get() to change values of tuple
    get<0>(geek) = 'b';
    get<2>(geek) =  20.5;

This code to me is equivalent to doing a type cast from an array, list,
vector, or map if one needs to pass/return multiple values.

**Comment by iahung2** [comment]
The syntax is so ugly compared to .NET's. I think I don't want it.

**Comment by objeck** [comment]
OK, understand I am not trying to recreate .Net or Java. I started the project in 2008 because I thought Java was too bloated. At that time, C# was Windows specific and Objeck relied heavily on Linux and macOS. 

I would argue that a general purpose language only needs to implement primitives, lists, and maps to most solutions.

**Comment by iahung2** [comment]
> OK, understand I am not trying to recreate .Net or Java.

Yes, I understand. And I don't want to bring .NET or Java to Objeck, too.

> I would argue that a general purpose language only needs to implement primitives, lists, and maps to most solutions.

You are right about that. But, this is more right when apply to scripting languages. And Objeck is not a scripting language.

`Tuples` have their own usages. I decided to drop the feature request for `Tuples` because at the moment I can substitute it with other data structures. I also dislike the ugly syntax of Java and C++. You said, Objeck also uses type erasure like them, so, I guess the Objeck implementation will have an ugly syntax, too. But, I don't dismiss the needs for `Tuples`. The more you explore with AI and ML, the more you will find they use `Tuples` very often. I read a lot of code, even thought I don't understand most, I do recognize the patterns. Maybe you will add `Tuples` in the future because of your own needs.
