### ISSUE TITLE
What is `Collection.Hash` used for?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#441]
Please pardon this stupid question. I'm very dumb about DT&Algorithms. How is it differed from other Collection types? For example, `Collection.Map` and `Collection.MultiMap`?

**Comment by objeck** [comment]
The Collection.The map is an ordered binary tree with a 1:1 mapping of keys to values. The Collection.MultiMap class allows multiple values for a single key.

**Comment by iahung2** [comment]
> The Collection.The map is an ordered binary tree with a 1:1 mapping of keys to values. The Collection.MultiMap class allows multiple values for a single key.

I want to ask what `Collection.Hash` is used for.

**Comment by objeck** [comment]
Sorry, the `Hash` class is a generic hash table implementation.
