### ISSUE TITLE
What is `Collection.Cache` used for?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#442]
Please pardon this stupid question. I'm very dumb about DT&Algorithms. How is it differed from other Collection types? For example, `Collection.Map` and `Collection.MultiMap`?

Btw, is it ordered or unordered?

**Comment by objeck** [comment]
The Cache class is used to store/cache X number of items. Consider a website where one wants to cash X number of webpages. The items are unordered.
