### ISSUE TITLE
Please add `Collection.UnorderedSet`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#448]
Delphi's `Set` data type is unordered. `Collection.UnorderedSet` helps porting Delphi code.

**Comment by objeck** [comment]
Thanks, I will look into this further

**Comment by objeck** [comment]
This would end being a specialized version of the `MultMap` class.

**Comment by iahung2** [comment]
> This would be an invert of the `MultiMap` with keys instead of values. Is this what you're looking for?

I don't know. I don't know the underlying of the data structures I'm using. It's like this. There is a tutorial of the language, Delphi in this case. The tutorial talks very few about the data structures and tell me how to use them and which should be used for a specific purpose. I blindly follow the tutorial. I have never been trained in CS and I'm a pure hobbyist. I bought some programming books but have never seriously read them. The DT&Algorithms stuffs make me headache. The only material I relying entirely on are simple tutorials in the internet. This is the very reason why it's so hard for me to utilize Objeck. There is no such tutorial exists for Objeck. Getting Started doesn't count. It's too few on the details. You can just think I'm a loser and ignore this. I'm having a headache now.

**Comment by objeck** [comment]
Not at all, thank you for the feedback. 

Objeck was designed as a minimalistic language. I believe I have not achieved this goal as more Features are added with minimal benefit. I observe this trend in Java as well C#, and wanted to avoid it.

**Comment by iahung2** [comment]
> Objeck was designed as a minimalistic language. I believe I have not achieved this goal as more features are added with minimal benefit. I observe this trend in Java as well C#, and wanted to avoid it.

Objeck is still minimalism. Most of the features added are to the libraries, not the language itself. Objeck is too minimalism. It even lacks the most basic math functions! It's me that asked you to add them. I still remember. The only thing that I think could be considered as with minimal benefit is the symlinks and hardlinks classes I asked you to add to System.IO.Filesystem. This is my bad.

**Comment by iahung2** [comment]
Why do you reopen this issue? I'm not even sure what I'm wanting. I'm not asking for something exactly the same as Delphi's Set data type. Delphi's Set is implemented using bitmask (I got this from Google, and I admit I don't understand, but with the limit of 256 elements of it then it's very useless for Objeck). What I'm thinking is simple. The nature of Delphi's Set is unordered. Objeck's Set is ordered. If Objeck has an unordered Set, the code could map 1:1 easier. But frankly speaking, most of the Delphi code using Sets I know, they will work exactly the same regardless of Set is ordered or unordered. I think I need to think twice before opening any feature requests. I'm sorry.

**Comment by objeck** [comment]
Thanks for the feedback, implementing an unordered map is not difficult however it requests time to implement. I have not come across a used case for such a data structure.

Please do not take my feedback as criticism as many of your requests have been implemented.

**Comment by iahung2** [comment]
Oops, C++ has `unordered_set`!

https://www.geeksforgeeks.org/unordered_set-in-cpp-stl/

I have never fully know all of the C++ containers, though. Most of the time I use `std::vector` and `std::unordered_map`.

**Comment by iahung2** [comment]
> Please do not take my feedback as criticism as many of your requests have been implemented.

Yes, I know. It's only me that know I'm a bad coder. I have never take your feedback as criticism.

**Comment by objeck** [comment]
In C++, an unordered_set contains keys while an unordered_map contains keys
and values. The implementations are nearly identical.

**Comment by iahung2** [comment]
So this mean implementing of `Collection.UnorderedSet` is very easy to you? I dropped the request for Tuples. Please reconsider the unordered maps in #451 and `Collection.UnorderedSet`. As I have read on various tutorials in the internet and I strictly followed them, unordered containers have their own performance benefits. If you can, why don't we have both ordered and unordered?

**Comment by objeck** [comment]
Maybe this is semantics, consider using the Hash class as it is an
unordered collection of keys. I thought you were asking for a data
structure that contains multiple keys with no associated values.

Can you please clarify?

https://www.geeksforgeeks.org/map-vs-unordered_map-c/amp/

**Comment by objeck** [comment]
Add `SetHash` to support `unordered_map` like C++ functionality.

**Comment by iahung2** [comment]
Time will tell if what you added is what I really need or not. Real usage will tell everything. I'm confused by all of this terminology. I can't answer most of your questions. Mostly because I have no ideas. I guess you will find it annoying when talking with stupid people like me. I'm sorry for wasting your time.
