### ISSUE TITLE
Generate app. exe for windows

### ISSUE THREAD

**Issue by Spoiledpay** [objeck/objeck-lang#45]
Dear, the new language, does it generate .exe app for windows? Informs that using -tar exe can generate or get it wrong.?

obc -src Hello.obs -tar "exe"

**Comment by objeck** [comment]
Hi Spoiledpay, 

The ``-tar`` option allows programmers to specify a target format such as a VM executable using the ``-tar exe`` option. Another output format is a library which, requires the ``-tar lib`` option. In general, the ``-tar`` option is not needed to compile programs.

Here's an example of compiling [sample](https://github.com/objeck/objeck-lang/blob/master/programs/deploy/http_regex_9.obs) code:
1. ``obc -src http_regex_9.obs -lib net,regex`` compiles the source and includes the two required libraries for regex and HTTPS support
2. The output from the above is ``http_regex_9.obe`` a VM executable
2. The binary can be executed using ``obr http_regex_9``

Check out the [getting started](https://www.objeck.org/getting_started.html) guide for more, or let me know if you have additional questions.

Cheers,
Randy

**Comment by Spoiledpay** [comment]
Hi, 
So we can say that it resembles the Java language. It does not generate a native windows application. Like hello.exe. Where can be run from the command line just as c:\hello.exe

Can you confirm what I said or she has a way to generate pure and native executables. And not being interpreted as java -tar hello.jar

thanks

Fernando Dantas

**Comment by objeck** [comment]
Hi Fernando, 

You are correct; the compiler generates bytecode like Java, not platform-specific executables. A *.obe file is similar to a *.jar file containing all code needed to run a program using a VM.

Thanks,
Randy
