### ISSUE TITLE
Please add unordered map

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#451]
`Collection.UnorderedMap`, `Collection.UnorderedMultiMap`, and `Collection.UnorderedHash`?

C++ offers both ordered and unordered map.

**Comment by objeck** [comment]
In C++, the ordered `map` is a hash. A tree structure backs an `unordered_map`.

**Comment by iahung2** [comment]
> In C++, an unordered `unordered_map` is a hash. A sorted tree structure backs a `map.`

Perhaps I shouldn't mention C++. Put C++ aside. My idea is, if there is ordered maps, there should be unordered maps, too. Should Objeck have unordered maps? Languages usually offer both. At least, this is what I read about Java and C#.
