### ISSUE TITLE
Support "response files"

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#454]
On some systems (such as older UNIX systems and certain Windows variants) command-lines have relatively limited lengths. Windows compilers therefore support "response files". These files are mentioned on the command-line (using the "@file") syntax. The compiler reads these files and inserts the contents into argv, thereby working around the command-line length limits.

https://stackoverflow.com/questions/61799140/is-it-possible-to-put-a-bunch-of-wno-gcc-flags-into-a-file-and-reference-th

**Comment by objeck** [comment]
Added

**Comment by objeck** [comment]
Implemented: pass the ``@filename`` as 1 parameter on the command line after the name of the program.
