### ISSUE TITLE
Serializing/Deserializing Objeck object to/from JSON

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#456]
The idea is to be able to send/receive Objeck objects between processes, over the network,...

**Comment by objeck** [comment]
Just data?

**Comment by iahung2** [comment]
> Just data?

I think so.

**Comment by objeck** [comment]
JSON elements would have to map to the existing ``Collection`` classes.

**Comment by iahung2** [comment]
> JSON elements would have to map to the existing `Collection` classes.

https://github.com/objeck/objeck-lang/issues/421
https://github.com/objeck/objeck-lang/issues/422

**Comment by iahung2** [comment]
https://github.com/objeck/objeck-lang/issues/384
https://github.com/objeck/objeck-lang/issues/385
https://github.com/objeck/objeck-lang/issues/398

**Comment by objeck** [comment]
I will defer this; it seems like a "nice to have," which I do have time to implement. Please, refer to the prior comment.

**Comment by objeck** [comment]
What about type-checking? Generate an exception if the wrong data type is cast? The existing `JsonElement` class supports a type and a value.

**Comment by iahung2** [comment]
> After looking into this more...
> 
> What about type-checking? Generate an exception if the wrong data type is cast?
> 
> The existing `JsonElement` class supports a type and a value. In dynamically typed languages, a value is a type/value. However, a value must map to a type in statically typed languages, which requires runtime type checking.
> 
> What is your proposed solution?

Does Objeck support `Reflection`? What does `System.Introspection` do?

Does Objeck support something equivalent?

https://www.geeksforgeeks.org/typeof-operator-keyword-in-c-sharp/

Btw, yes, this is the advantage of a language that supports exceptions. Everything is so much easier with exceptions.

https://code-maze.com/csharp-how-to-ensure-a-string-is-valid-json/

**Comment by iahung2** [comment]
I know you will never add support for exceptions, so I will close this.

**Comment by objeck** [comment]
Objeck supports reflection via the ``System.Introspection`` class; however, that is not tied to supporting exceptions. In my professional experience, most developers either log or throw exceptions versus writing proper error-handling routines.
