### ISSUE TITLE
Call arbitrary DLL using System.API.DllProxy

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#457]
Is it possible? This is not a feature request. It's only a question.

From the description of `DllProxy` class:

`Class allow programmers to load native shared libraries that can be called by Objeck classes. Programmers can call native C functions within these libraries.`

In nowhere it said that the shared libraries must be wrapped to Objeck-style plugin (`libobjk_something`) to be able to be used. So I can think that this class is possible to call arbitrary DLL. If it's not the case, please edit the document to make it clear.

**Comment by objeck** [comment]
Documentation updated
