### ISSUE TITLE
`Collection.Hash` vs `Collection.Map`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#460]
I'm totally ignorant about the algorithms underlying them and the use cases for each of them.

But this is what I observed.

I'm unable to have a `Collection.Map` with `1000000` elements. It always crashed with:

```
>>> call std::stack bounds have been exceeded! <<<
```

Increasing the value of `--GC_THRESHOLD` doesn't help.

But I'm able to have a `Collection.Hash` with `1000000` elements.

I have no idea why.

**Comment by objeck** [comment]
The call stack size is set to 32, rather small. I will create an enhancement to make the call stack and operation stack sizes configurable.

**Comment by objeck** [comment]
Tweaked the VM parameters yesterday to improve performance. The bottleneck was memory for both the `Map` and `Hash` classes when inserting 1 million elements.
