### ISSUE TITLE
Is it possible to compile multiple source files at once?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#461]
As I recall I have never seen `obc` compiles multiple source files at once. It's always a single source file. Is this supported?

**Comment by objeck** [comment]
Yes, here's an example.

``obc -src x.obs,y.obs -dest xy.obe``

**Comment by iahung2** [comment]
> Yes, here's an example.
> 
> `obc -src x.obs,y.obs -dest xy.obe`

Does something like `obc -src *.obs` work? Is the order of the source files matter?

**Comment by objeck** [comment]
No, the full file names must be provided

**Comment by iahung2** [comment]
> No, the full file names must be provided

Is the order of the source files matter?

**Comment by objeck** [comment]
No
