### ISSUE TITLE
Rename `Collection.Hash` to `Collection.HashMap`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#467]
To match the naming convention of C# and Java.

**Comment by iahung2** [comment]
I tested to insert `Nil` and it failed to run with `>>> Unable to resolve virtual method call <<<`. So, Objeck's `Hash` is equivalent to Java's `HashTable`. Should the new name be `HashTable` instead of `HashMap`?

https://www.geeksforgeeks.org/differences-between-hashmap-and-hashtable-in-java/

**Comment by objeck** [comment]
Thanks, this was fixed. the `Hash` class calls an object's `Hash(...)` method to obtain a semi-unique key. If the key value is `Nil`, the runtime cannot call the object's virtual method.
