### ISSUE TITLE
Add `Collection.MultiSet`

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#468]
Same as `Collection.Set` but allow duplicate elements.

**Comment by objeck** [comment]
I do not understand the request as a `Set` is a type of associative container that contains only unique elements because those elements are used as keys.

**Comment by iahung2** [comment]
> I do not understand the request as a `Set` is a type of associative container that contains only unique elements because those elements are used as keys.

https://www.geeksforgeeks.org/multiset-in-cpp-stl/
