### ISSUE TITLE
`Collection.Hash` doesn't preserve the order of the elements

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#473]
Yes, it doesn't sort everything like `Collection.Map`. But it doesn't preserve the order of the elements. I used a `for` loop to initialize the `Hash`, so I know the order of the elements.

**Comment by objeck** [comment]
Consider something like 

```
values := Collection.Vector->New()<Pair<String, IntRef>>;
values->AddBack(Collection.Pair->New("MC Eiht", 8)<String, IntRef>);
```
