### ISSUE TITLE
Verbatim strings

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#474]
I got the idea from C#:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim

C# interpolated strings started with `$` character:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

Objeck strings support interpolation by default, so you could reuse the `$` character, or simply use the `@` character like C#.

**Comment by iahung2** [comment]
If you don't like C#'s syntax, you could have a look at Go's backquoted strings. But Go's syntax has more limitations than C#'s:

https://stackoverflow.com/questions/4423951/how-to-put-a-backquote-in-a-backquoted-string

**Comment by objeck** [comment]
Thanks, if you want to start the implementation, I will help you as needed. 

You will probably need to start with [scanner](https://github.com/objeck/objeck-lang/blob/master/core/compiler/scanner.cpp#L1024) where escape characters are translated.
