### ISSUE TITLE
Compiler switch to disable Unicode operators

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#475]
IMO, they are ugly: https://github.com/objeck/objeck-lang/discussions/88

If I want to force a coding convention for my own code, I will not permit Unicode operators, and of course I don't want the contributors to use them, so a compiler switch to disable Unicode operators is very useful.

**Comment by objeck** [comment]
Funny, it was added as part of a coding challenge. Do not plan to change them, as they do not cause any harmful side effects.
