### ISSUE TITLE
Data Type Formatting Options

### ISSUE THREAD

**Issue by objeck** [objeck/objeck-lang#479]
We are misunderstanding each other. I'm asking for a way to format the output, similar to C's `printf`. The magic is really the `"%02x "` format specifier of `printf`. Objeck has nothing equivalent. Yes, I know the `ffffffffffffff` and the `00000000000000` are always there, but I should be able to format the output to not show them.

_Originally posted by @iahung2 in https://github.com/objeck/objeck-lang/issues/472#issuecomment-1964700156_

**Comment by objeck** [comment]
I am considering adding ``ToIntString()`` to the ``Char`` and ``Byte`` classes and ``ToCharString()`` to the ``Byte`` class.

**Comment by iahung2** [comment]
> I am considering adding `ToStringUnsigned()` to the `Char` and `Byte` classes.

No, please don't. You should better invest in `System.IO.Standard->SetIntFormat` and extend `System.Number->Format`. Please remove the useless `ToHexString` method you just added, too. It gives exactly the same output as `ToString`!

**Comment by objeck** [comment]
See #472
