### ISSUE TITLE
Bitwise NOT

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#480]
Don't see it on this table:

https://objeck.org/getting_started.html#operators

**Comment by objeck** [comment]
The unary bitwise `not `operation (i.e., one's complement) is not supported. I never needed to; it could be added as Objeck supports the logical `not `operator.

**Comment by objeck** [comment]
I am adding the `not` keyword

**Comment by objeck** [comment]
Ready for testing, the JIT code seems to be working on ARM64 and AMD64 targets.

**Comment by iahung2** [comment]
> I am adding the unary `not` keyword

Please give example code. I always have compilation error.

**Comment by objeck** [comment]
Stop insulting me!

**Comment by iahung2** [comment]
> Stop insulting me!

OK.
