### ISSUE TITLE
Can I change the directory structure of the Objeck distribution?

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#483]
Merge `app` and `bin` so `ObLauncher.exe` is now in `bin` together with `obc`, `obr`,...

Moving `doc` into `share/objeck/doc`.

Moving `examples` into `share/objeck/examples`.

Moving `LICENSE` and `readme.html` into `share/objeck`.

Moving and renaming `lib` into `lib/objeck`.

This is needed to install Objeck into `/usr` or `/usr/local`.

Note: This change is on the packager's side to create a directory structure that is compatible with the Linux/Unix FHS. This doesn't change the directory structure of the official Objeck distribution.

**Comment by objeck** [comment]
Yes, just ensure your PATH points ``xyz/bin`` and OBJECK_LIB_PATH  ``xyz/lib``.
