### ISSUE TITLE
Support legacy MSVCRT-based MinGW

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#493]
https://github.com/objeck/objeck-lang/issues/429

**Comment by objeck** [comment]
32-bit?

**Comment by iahung2** [comment]
> 32-bit?

Still 64-bit. You are using some APIs that are only available in UCRT. See: https://github.com/objeck/objeck-lang/issues/429

**Comment by objeck** [comment]
Sorry, I do not have the time to add another Windows environment.
