### ISSUE TITLE
Optimized builds

### ISSUE THREAD

**Issue by iahung2** [objeck/objeck-lang#496]
For example, AVX2 builds, like https://github.com/zufuliu/notepad2/releases

**Comment by objeck** [comment]
I do not understand: faster builds or a new build systems?

**Comment by iahung2** [comment]
> I do not understand: faster builds or a new build systems?

https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2

**Comment by objeck** [comment]
I need help understanding the context. On Intel, Objeck uses _advanced_ instruction sets like SSE3. Costly floating point vector operations (i.e., transpose, dot product, etc.) are delegated to the Eignen C++ library, which leverages local hardware like APUs and GPUs. The same goes for ARM64 support.

**Comment by iahung2** [comment]
No. This is not about how the JIT compiler of Objeck compiles bytecode into machine code. It's more simple. It's about building the Objeck binaries themselves (e.g: `obc`, `obr`,...) with advanced instruction sets like AVX2. It's a compiler switch just like `-O3`.

**Comment by objeck** [comment]
Added to AMD64 builds for Windows and Linux.
