### ISSUE TITLE
Does this project make use of any of these techniques?

### ISSUE THREAD

**Issue by chatchoi** [objeck/objeck-lang#504]
- Build with sanitizers
- Run static analyzers
- Memory profiling

It's kind of an interview question. Feel free to dismiss it.

**Comment by objeck** [comment]
Good questions, see below:

- Build with sanitizers: Yes, the project used Valgrind on Linux, Leaks on macOS, and similar tools on Windows
- Run static analyzers: Yes, Coverity and CodeQL
- Memory profiling: Yes, it was necessary to debug and optimize the memory manager

**Comment by chatchoi** [comment]
Sanitizers are ASan, UBSan,... Valgrind is a memory profiler.

**Comment by objeck** [comment]
Thanks. I enabled Ubsan on Linux GCC and will look to add the flag to automated builds.

**Comment by chatchoi** [comment]
There are other sanitizers that you could make use of, e.g., ThreadSanitizer, Memory and Address Sanitizers.

p/s: Thank you for your help. This is my homework. I need to ask some C++ projects to do a survey. I'm still a high school student and no expert at all. I myself don't understand anything about this stuff. Teacher asks me to do a survey so I do.
