### ISSUE TITLE
2d_game_13.obs not compile

### ISSUE THREAD

**Issue by chadchoi** [objeck/objeck-lang#506]
Use the command in 2d_game_13.obs itself:

obc -src 2d_game_13.obs -lib gen_collect,sdl_game,sdl2 -dest 2d_game_13.obe

Error:

Error: Unable to resolve external library class: 'Data.JSON.JsonParser'; check library path

**Comment by objeck** [comment]
Thanks try ````obc -src 2d_game_13.obs -lib gen_collect,json,sdl_game,sdl2 -dest 2d_game_13.obe````. The library missing is the JSON library.

**Comment by objeck** [comment]
Updated the compiler options in the source code comments.

**Comment by chadchoi** [comment]
The [latest release](https://github.com/objeck/objeck-lang/releases/tag/v2025.3.0) doesn't have binary builds, so I managed to build it from source on MSYS2 (UCRT). The build process is straight forward, but the compiler crashed when trying to compile `2d_game_13.obs`. Yes, `2d_game_13.obs` again.

Note: The compile command in `2d_game_13.obs` is wrong. It mistakenly set `2d_game_13.obs` as the output when the correct name should be `2d_game_13.obe`. This is too easy to spot so I have used the correct command from the beginning. The compiler crashed because it's buggy, not me using the wrong command.

**Comment by chadchoi** [comment]
Almost forgot, I cloned your latest code from Github. The last commit was 1 hour ago.

**Comment by chadchoi** [comment]
There are so many great features touted in README.md that made me fooled. These features are nothing if the most basic functionality doesn't work.

**Comment by chadchoi** [comment]
Even `hello_0.obs` failed to compile. The compiler will crash with whatever source file I give it. I have the impression that you only push code into Github without doing any tests to see if your code is working or not. Everything is so good on paper but in reality nothing works!

**Comment by chadchoi** [comment]
A lot of micro commits create the impression that the project has many commits and thus active developed. But if you stash these micro commits together to create a meaningful commit instead, the number of commits will decrease at least 10x!

I can't imagine that put a dot into a comment worth its own commit!

**Comment by chadchoi** [comment]
Either the support for MSYS2 is broken or the compiler itself is very buggy.
