### ISSUE TITLE
A launcher of somesort

### ISSUE THREAD

**Issue by Souphgdhgdghgdhdg** [objeck/objeck-lang#67]
it would be cool to be able to make a exe that launches a `.obe` instead of the user needing `obr`

**Comment by objeck** [comment]
Would embedding the runtime with a file association for Windows work?

- User installs runtime, or it is embedded in an archive
- The ``.obe`` file type is registered with Windows
- User clicks or type a ``.obe`` file which invokes the runtime

**Comment by Souphgdhgdghgdhdg** [comment]
hmm i think it would work, but what i want is:

* user double clicks the exe
* launches the obe file next to it
something like launch4j (but for objeck)

**Comment by objeck** [comment]
Thanks, the feedback helps. I will look into a solution. In the interim, I added a file association for ".obe" file types.

**Comment by objeck** [comment]
Working on it [here](https://github.com/objeck/objeck-lang/tree/embed_launcher/core/native_launcher). The solution is an embedded runtime with a native launch binary. If you bring over all the dependencies on Windows, it is a base 8 MB file system (mostly due to SDL2 DLLs). If you strip SDL2 DLLs, like on Linux, it is a 2.5 MB base image.

**Comment by objeck** [comment]
This solution seems doable. 

However, I want to leave clues to the programmers that they are running in this environment and that resources may be located in a different area. The plan is to set up a "Property" for this configuration that points to the new root. Traditionally, using "Runtime->GetInstallDir()" worked for the location of dependent resources.

Also need to document the directory structure for feedback. 

Directory structure prototype:
[root]
  apps\app.obe
  apps\[resources]
  runtime\bin\obr
  runtime\lib\native\[*.dll,*.so]
  runtime\lib\sdl\font\[*.ttf]
  *** Start: For windows ***
  runtime\lib\sdl\[*.dll]
  *** End: For windows ***

**Comment by objeck** [comment]
Windows example, 90% was generated by code. I copied the *.obe file under the app vs. getting it as a parameter. I renamed obn.exe to hello.exe vs. getting it a parameter. Making these code updates is minor.

[hello.zip](https://github.com/objeck/objeck-lang/files/9647179/hello.zip)

**Comment by Souphgdhgdghgdhdg** [comment]
awesome, this is what i meant, when will it be ready?

**Comment by objeck** [comment]
It should be delivered in the next couple of days. I need to test/tweak the code for Linux and macOS. Last test compatibility with programs that have multiple files such as games.

**Comment by objeck** [comment]
Added in 7c70ac59358d31e1c5bfdc64301e635dde26d83a as part of master. Will be delivered in the next release

**Comment by objeck** [comment]
Will be pushed with v6.8.0

**Comment by objeck** [comment]
Added to release [6.8.0](https://github.com/objeck/objeck-lang/releases/tag/v6.8.0)
