### ISSUE TITLE
MSYS2 support

### ISSUE THREAD

**Issue by 1e9t8m29** [objeck/objeck-lang#71]
For unknown reasons, my @ruanjiasing account being flagged by github and hidden from the public. I can't see your replies. I created a new ticket to continue our previous discussion @objeck @rhollines

**Comment by objeck** [comment]
The compiler and VM build under msys2. Refer to the 'make/Makefile.msys2.amd64' build files. The VM is behaving oddly, have not had time to set up a debug environment.

**Comment by objeck** [comment]
The compiler, VM, and debugger now build on msys2; refer to the bottom of the main page. I will add build support for the supporting native Objeck libraries before the next release.

**Comment by objeck** [comment]
The complete toolchain can now be built under UCRT64 MSYS2.
