### ISSUE TITLE
Editors and IDEs support?

### ISSUE THREAD

**Issue by 1e9t8m29** [objeck/objeck-lang#72]
It seems there is none at the moment. I suggest adding at least syntax highlighting to CudaText: https://github.com/Alexey-T/CudaText

CudaText is inspired by SublimeText but is more lightweight and available for more platforms.

**Comment by objeck** [comment]
Please refer to 'objeck-lang/blob/master/docs/syntax/howto.html' file. There is support for Visual Studio Code, Sublime (my primary), Notepad++, BBEdit, and gEdit.

**Comment by objeck** [comment]
There is LSP support for Visual Studio Code for Sublime (https://github.com/objeck/objeck-lsp)

**Comment by objeck** [comment]
There is LSP support for Visual Studio Code for Sublime (https://github.com/objeck/objeck-lsp). I am currently working on LSP codeAction support. This will allow the user to click on an error and select a 'quick fix' if available.
