### ISSUE TITLE
what's going on my friend?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#73]
I'm almost fell to the ground after I read this makefile:

https://github.com/objeck/objeck-lang/blob/master/core/compiler/make/Makefile.msys2.amd64

man, do you know how to use msys2? you are mixing dlls from different msys2 environments. it's unbelievable that you can get it built. it's not for no reasons your vm is behaving oddly. @objeck @rhollines 

https://www.msys2.org/docs/environments/

**Comment by iahung** [comment]
> Ha, no have never used msys2. Have stuck to VS and native GCC/clang compilers for Linux and macOS. Can you provide updates to the Makefile?

Why do you need to cp the dlls into . (aka the current dir)? If you run the binary from msys2 mingw64 shell, you don't need to do so. The key is using the correct shell and only the environment provided by that shell (mingw64). If you want to run the binary outside the msys2 shell, just add C:\msys64\mingw64\bin to PATH (Windows) and done. I'm new to this project and I don't even know how to trigger a build. There are various makefiles. Where to start? Is there any build script?

If the sole purpose for you to cp the dlls into . is to resolve dependencies then just remove all these cp lines from your makefiles. Rebuild and run the binary the proper way as I said above and see if it's still behaving oddly or not.

**Comment by objeck** [comment]
Thanks, I will look into this. Build instructions are at the bottom of the main page. Support Xcode, VS, and GCC.

**Comment by iahung** [comment]
> Thanks, I will look into this. Build instructions are at the bottom of the main page. Support Xcode, VS, and GCC.

So use the guide for Linux on msys2?

**Comment by objeck** [comment]
Thanks for the feedback.

The compiler, VM, and debugger now build on msys2; refer to the bottom of the main page. I will add build support for the supporting native Objeck libraries before the next release.
