### ISSUE TITLE
does it require ucrt?

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#74]
I found you are using ucrt64 environment of msys2. Does the msvcrt environment (mingw64) not work? @objeck @rhollines

**Comment by objeck** [comment]
The toolchain only compilers and runs under UCRT64 as it requires UTF-8 locale and C++17 support. The VM also uses a handful of newer Win64 APIs.

**Comment by objeck** [comment]
Last, the complete toolchain can now be built under MSYS2.
