### ISSUE TITLE
Try the Clang64 shell

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#75]
It's also UCRT based even though not explicitly stated @objeck @rhollines 

Just change the prefix mingw-w64-ucrt-x86_64- to mingw-w64-clang-x86_64- to have the package name.

**Comment by iahung** [comment]
No need to change makefiles from gcc/g++ to clang/clang++. Clang64 shell provides fake gcc/g++ that are actually symlinks to clang/clang++. So no need to change makefiles regarding this.

**Comment by iahung** [comment]
Of course your msys-ucrt64.zip will not work with clang64 shell, you have to make another msys2-clang64.zip :smile:

**Comment by objeck** [comment]
Thanks, I called out that the dlls are for the ucrt64 environment

**Comment by iahung** [comment]
> Thanks, I called out that the dlls are for the ucrt64 environment

Did it work with the Clang64 shell?

**Comment by iahung** [comment]
I don't see msys-clang64 on the lib directory, only msys-ucrt64. README.md also has no mentions of Clang64. So it failed to work with Clang64? Could you tell me where it failed? Thank you.

**Comment by objeck** [comment]
@iahung would you like to become the maintainer, and contributor, for MSYS2 support? I am currently maintaining the existing toolchain across 3 OSs and 2 CPU targets. I have limited time to add and test additional platforms.

**Comment by iahung** [comment]
> @iahung would you like to become the maintainer, and contributor, for MSYS2 support? I am currently maintaining the existing toolchain across 3 OSs and 2 CPU targets. I have limited time to add and test additional platforms.

If it's only about testing (building on msys2 to see if it works), I could do. I'm more a packager (someone who builds people's code and make a package) than a coder. I'm very bad at coding even though sometimes I patched people's code to build.

**Comment by objeck** [comment]
@iahung, it would be help with testing and packaging. In the winter I will add clang64 shell support.

**Comment by objeck** [comment]
MSYS2 Clang64 build support was added
