### ISSUE TITLE
Combine all pacman commands into a single commands

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#76]
pacman supports install multiple packages the same time @objeck @rhollines 

No need to run each command to install each package like that.

**Comment by iahung** [comment]
This command worked for ucrt64:

`pacman --noconfirm -S mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-openssl make mingw-w64-ucrt-x86_64-SDL2 mingw-w64-ucrt-x86_64-SDL2_ttf mingw-w64-ucrt-x86_64-SDL2_mixer mingw-w64-ucrt-x86_64-SDL2_image mingw-w64-ucrt-x86_64-unixodbc`

**Comment by iahung** [comment]
This command worked for clang64:

`pacman --noconfirm -S mingw-w64-clang-x86_64-gcc mingw-w64-clang-x86_64-openssl make mingw-w64-clang-x86_64-SDL2 mingw-w64-clang-x86_64-SDL2_ttf mingw-w64-clang-x86_64-SDL2_mixer mingw-w64-clang-x86_64-SDL2_image mingw-w64-clang-x86_64-unixodbc`

**Comment by objeck** [comment]
Awesome, thank you, I will add this to the docs before the next release.

**Comment by objeck** [comment]
Added to the main page

**Comment by iahung** [comment]
> This command worked for clang64:
> 
> `pacman --noconfirm -S mingw-w64-clang-x86_64-gcc mingw-w64-clang-x86_64-openssl make mingw-w64-clang-x86_64-SDL2 mingw-w64-clang-x86_64-SDL2_ttf mingw-w64-clang-x86_64-SDL2_mixer mingw-w64-clang-x86_64-SDL2_image mingw-w64-clang-x86_64-unixodbc`

@objeck @rhollines Please use this combined command instead of many individual commands for clang64.
