### ISSUE TITLE
Objeck lexer for CudaText (free editor)

### ISSUE THREAD

**Issue by Alexey-T** [objeck/objeck-lang#77]
To install lexer: "Plugins / Addons Manager / Install", find Objeck item.

![obj-l](https://user-images.githubusercontent.com/4154978/203281495-e95d21ae-9e3e-45bf-8d24-5451139d1a3a.png)

**Comment by iahung** [comment]
@objeck @rhollines Please add this into documents. Thank you.

**Comment by objeck** [comment]
Thanks, closing this
