### ISSUE TITLE
Release 6.9.0's version is 0.0.0

### ISSUE THREAD

**Issue by hgntn** [objeck/objeck-lang#81]
Previous release 6.8.6 version is correct.

**Comment by objeck** [comment]
Fixing that now, it now did run the update script

**Comment by objeck** [comment]
https://github.com/objeck/objeck-lang/blob/v6.9.0/programs/util/deploy_rename.obs

**Comment by hgntn** [comment]
@objeck Same problem happen with release 2023.3.0's version.

**Comment by objeck** [comment]
Thanks, fixed
