### ISSUE TITLE
A minor problem on docs/readme.html

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#83]
The directory `objeck-lang\lib\sdl` doesn't contains anything other than the `fonts` directory. There is no binaries. Why users have to add it to PATH on Windows? On other platforms (Linux and macOS), the directory `objeck-lang/lib/sdl` is not added to PATH. So is it just a minor mistake or it's just different on Windows?

**Comment by objeck** [comment]
Huh, did you install it from the .zip or .msi file?

**Comment by iahung** [comment]
> Huh, did you install it from the .zip or .msi file?

Compile from source. I'm on MSYS2. I think .zip or .msi is for MSVC? So the guide is for MSVC only?

**Comment by iahung** [comment]
Almost forgot @objeck @rhollines you have another mistake in source file name too. It's encrypt_7.obs not encrypt.obs

**Comment by objeck** [comment]
Thanks! Made those updates (68eb7088f)

**Comment by objeck** [comment]
If you are running under MSYS2 there is no need to add the `objeck-lang/lib/sdl` path. The SLD2 DLLs should already be in the MSYS2 shell's path.

**Comment by objeck** [comment]
Released v6.9.1 with updated documentation.
