### ISSUE TITLE
UCRT64 based Objeck doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#84]
Compilation of Objeck itself is always fine. Today I managed to try compiling an example. I have properly set everything up as your guide. But what I see is "Objeck Compiler has stopped working". UCRT64 based binaries on `msys64/ucrt64/bin` work fine on my system. Only Objeck Compiler crashing. But a simple `obc -v` doesn't crash it. It correctly showed the message. But `obc -src sth` will always crash it.

**Comment by iahung** [comment]
Surprising enough @objeck @rhollines CLANG64 based Objeck worked fine on my Windows 8.1. What's wrong with UCRT64 based Objeck?

**Comment by objeck** [comment]
I tested the current MSYS2 system on Windows 10. I get the following after building and executing `./obc -v` command.

![Screenshot 2022-11-30 123257](https://user-images.githubusercontent.com/989681/204902601-1d549d1d-d922-4085-9d23-00075953b389.png)

**Comment by iahung** [comment]
> I tested the current MSYS2 system on Windows 10. After building and executing the `./obc -v` command it worked (see attached). When I tried to install MSYS2 on Windows 7, I got a message stating that Windows 7 and 8 support was being deprecated in 2022.
> 
> ![Screenshot 2022-11-30 123257](https://user-images.githubusercontent.com/989681/204902601-1d549d1d-d922-4085-9d23-00075953b389.png)

What important is it works or not. Is it able to compile hello_0.obs or it crashed? The message about deprecation is bogus, you could ignore it. Microsoft is just urging you to upgrade to Windows 10+. Many computers stuck with Windows 7 and some stuck with Windows 8.1, most of the people I know running such a system have already disabled Windows Updates for years, so they will not get such deprecation message.

**Comment by iahung** [comment]
Btw I use the normal Windows Command Prompt not MSYS2 shell to compile the example.

**Comment by objeck** [comment]
Try the UCRT64 shell, add the `objeck/bin` directory to the path, and set the OBJECK_LIB_PATH environment variable path (i.e., `objeck/lib`). If you run from the Windows Command Prompt, you must also add the `\msys64\ucrt64\bin` directory to the path.

**Comment by iahung** [comment]
> Try the UCRT64 shell, add the `objeck/bin` directory to the path, and set the OBJECK_LIB_PATH environment variable path (i.e., `objeck/lib`). If you run from the Windows Command Prompt, you must also add the `\msys64\ucrt64\bin` directory to the path.

I have msys64\ucrt64\bin added to PATH. As I said, UCRT64 based programs (on msys64\ucrt64\bin) worked fine (on Windows Command Prompt).

**Comment by objeck** [comment]
Ok got it. I am setting up a Windows 8.1 HyperVisor (currently installing updates) and will do some spot-testing.

**Comment by objeck** [comment]
I built and ran the toolchain on a fully updated version of Windows 8.1 64-bit. The toolchain ran under the UCRT64 and Clang64 shells.

![Screenshot 2022-11-30 170250](https://user-images.githubusercontent.com/989681/204941036-7bb035ba-724e-4c9c-b0f1-159af8092259.png)

**Comment by iahung** [comment]
@objeck @rhollines I didn't notice it. My UCRT64 based Objeck worked under the UCRT64 shell too. But it doesn't work without the UCRT64 shell. If you call it from Windows Command Prompt it will crash. Please test.

**Comment by objeck** [comment]
What CPU are you running on?

**Comment by iahung** [comment]
I found the problem. I have another program installed added to PATH. This program ships it version of the MinGW-w64 libraries (it's normal MinGW-w64 like what of the MinGW64 shell). It conflicted with the libraries on msys64\ucrt64\bin as msys64\ucrt64\bin is added after it on PATH so it takes precedent (Windows will search it for libraries before msys64\ucrt64\bin). The solution is moving it behind msys64\ucrt64\bin on PATH. Everything worked now.
