### ISSUE TITLE
Deploying on MSYS2

### ISSUE THREAD

**Issue by iahung** [objeck/objeck-lang#89]
I used to think Objeck is a compiled to C language (Objeck compiler compiled Objeck code to C/C++ code and use C/C++ compiler to generate binaries). But it turned out to be wrong. Objeck is kind of like Java. This make my comments about msys-ucrt64.zip and msys-clang64.zip obsolete. Sorry about that.

I don't suggest you to revive these zips but instead now taking the needed dlls directly from the MSYS2 installation (will have to doing so each time the users run the deploy shell script to sync with the latest dlls from MSYS2). This way the users no longer have to add MSYS2's bin directory to PATH (msys64\ucrt64\bin or msys64\clang64\bin) and can really run Objeck standalone from MSYS2.

Please have a look at this. Thanks @objeck @rhollines

**Comment by objeck** [comment]
So, the entire "bin" directory must be zipped up for Clang64 or MSYS64. Doing so makes the distro very large.

**Comment by objeck** [comment]
There is a "native" Windows distro. If one wants to build and deploy on MSYS64, one must have the required libraries installed on their machine. Putting the required MSYS "bin" directory in one's path instead of copying the files to the deployment directory seems appropriate.

**Comment by iahung** [comment]
> So, the entire "bin" directory must be zipped up for Clang64 or MSYS64. Doing so makes the distro very large.

No, not the entire bin directory. Did you remember about your msys-ucrt64.zip and msys-clang64.zip? Only a handful of DLLs!
