### ISSUE TITLE
Objeck syntax highlighting file for TextAdept

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [objeck/objeck-lang#93]
This is my preprimary version. It's only partially working. I'm unable to improve it any further :disappointed: 

[objeck.lua.txt](https://github.com/objeck/objeck-lang/files/10252494/objeck.lua.txt)

The file name is objeck.lua, move it to textadept/lexers directory (textadept is the directory you extracted from their zip distribution).

Currently have to use Buffer -> Select Lexer... -> objeck each time you opened a source file to get syntax highlighting working.

I'm waiting for the TextAdept developer's answer so this could be changed.

Update: https://github.com/orbitalquark/textadept/discussions/312

Update: Edit -> Preferences -> it will open an init.lua file, put this line into this file and save:

`lexer.detect_extensions.obs = 'objeck'`

Quit TextAdept, the next time you launch it, it will automatically highlights obs source file.

**Comment by nsgnkhibdk2cls0f** [comment]
Need help with the regexes and reorganizing of the keywords @objeck :disappointed:

**Comment by 1997tn** [comment]
Should be closed now @objeck, see: https://github.com/iqskpduswupkcjqg/textadept-objeck-lexer

**Comment by 1997tn** [comment]
Should be closed now @objeck, see: https://github.com/iqskpduswupkcjqg/textadept-objeck-lexer

**Comment by objeck** [comment]
Thank you!
