### ISSUE TITLE
Minor bug on Sublime syntax file

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [objeck/objeck-lang#94]
At line 130, it should be `#` not `$`.

https://github.com/objeck/objeck-lang/blob/master/docs/syntax/sublime/objeck.sublime-syntax

**Comment by objeck** [comment]
Doing so breaks the syntax file

**Comment by objeck** [comment]
Going to close this, I tested the change; however, it broke the grammar.

**Comment by nsgnkhibdk2cls0f** [comment]
> Doing so breaks the syntax file

> Going to close this, I tested the change; however, it broke the grammar.

But the syntax for single-line comment is `#` and not `$` isn't it? These lines are:

```
  line_comment:
    - meta_scope: comment.line.objeck-obs
    - match: $
      pop: true
```

So single-line comment should be broken on Sublime isn't it @objeck? If replace `$` with `#` to correct it broken the grammar, then Ruby's grammar should be broken too as it also uses `#` for single-line comment!
