### ISSUE TITLE
Objeck syntax highlighting file for Lite XL

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [objeck/objeck-lang#95]
It's working well enough for me even though some features are not yet implemented, need your help @objeck to complete it.

[language_objeck.lua.txt](https://github.com/objeck/objeck-lang/files/10253313/language_objeck.lua.txt)

The file's name is language_objeck.lua, put in on lite-xl/data/plugins directory.

p/s: download Lite XL here: https://github.com/lite-xl/lite-xl

**Comment by 1997tn** [comment]
Should be closed now @objeck, see: https://github.com/iqskpduswupkcjqg/lite-xl-objeck-lexer

**Comment by objeck** [comment]
Should be closed now [@objeck](https://github.com/objeck), see: https://github.com/iqskpduswupkcjqg/lite-xl-objeck-lexer
