### ISSUE TITLE
Objeck syntax highlighting for JEdit

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [objeck/objeck-lang#97]
I'm using JEdit on Windows, data directory is `%appdata%\jEdit`. Put `objeck.xml` on `%appdata%\jEdit\modes` and edit/create if not exists the file named `catalog`:

```
<?xml version="1.0"?>
<!DOCTYPE MODES SYSTEM "catalog.dtd">

<MODES>

<!-- Add lines like the following, one for each edit mode you add: -->
<!-- <MODE NAME="foo" FILE="foo.xml" FILE_NAME_GLOB="*.foo" /> -->

<MODE NAME="objeck" FILE="objeck.xml" FILE_NAME_GLOB="*.obs" />

</MODES>
```

[objeck.xml.txt](https://github.com/objeck/objeck-lang/files/10259509/objeck.xml.txt)

Syntax highlighting works pretty good for me, except I think I organized the keywords not very right. This needs you to review and tweak it @objeck 

Update: almost forgot, please review and fix the regexes too. I don't understand regexes, so I keep them as is. The syntax highlighting file is based on CSharp.

**Comment by PHdrr** [comment]
@objeck Done: https://github.com/PHdrr/jedit-objeck-mode/blob/main/objeck.xml

**Comment by objeck** [comment]
Thank you! I will close the ticket.
